import type { Item, ItemTier, ArmorSet } from '../../../types/module'
import type { WeaponProperty } from './weapons'

// ─── Armor Properties ────────────────────────────────────────────────────────

export const armorProperties: WeaponProperty[] = [
  { id: 'bulky',             name: 'Bulky',             shortDescription: 'Disadvantage on Stealth and Acrobatics.',                         fullDescription: 'Disadvantage on Stealth checks and Acrobatics checks. The armor is loud, heavy, and obvious.' },
  { id: 'cumbersome',        name: 'Cumbersome',        shortDescription: 'Speed reduced by 5 ft.',                                           fullDescription: 'Reduces your movement speed by 5 feet. The armor\'s weight slows you down.' },
  { id: 'sealed',            name: 'Sealed',            shortDescription: 'Immune to gas, toxins, vacuum (4 hr air).',                        fullDescription: 'Environmentally sealed with its own air supply (4 hours). Immunity to inhaled toxins, gas, airborne diseases, and vacuum exposure while sealed.' },
  { id: 'intimidating',      name: 'Intimidating',      shortDescription: 'Advantage on Intimidation.',                                       fullDescription: 'Advantage on Intimidation checks. The armor\'s appearance inspires fear.' },
  { id: 'powered',           name: 'Powered',           shortDescription: 'Removes STR req, +1 melee damage, size +1 for carrying.',          fullDescription: 'Internal power source enhances strength. Removes STR requirements, +1 to melee damage, count as one size larger for carrying capacity. Requires power cells (1 per 24 hours).' },
  { id: 'thermally-shielded',name: 'Thermally Shielded',shortDescription: 'Resistance to fire damage.',                                      fullDescription: 'Resistance to fire damage. The armor is lined with heat-dispersing materials.' },
  { id: 'null-shielded',     name: 'Null-Shielded',     shortDescription: 'Advantage on saves vs psychic/warp.',                             fullDescription: 'Advantage on saves against psychic powers and warp effects. Incorporates null-field emitters or hexagrammic wards.' },
  { id: 'ablative',          name: 'Ablative',          shortDescription: 'Reduce first damage each combat by 1d6.',                          fullDescription: 'The first time you take damage each combat, reduce that damage by 1d6. Resets after a short rest (field repairs).' },
  { id: 'reinforced',        name: 'Reinforced',        shortDescription: 'Crits treated as normal hits.',                                    fullDescription: 'Critical hits against you are treated as normal hits (no bonus damage dice). Layered construction prevents penetrating blows.' },
  { id: 'lightweight',       name: 'Lightweight',       shortDescription: 'No speed penalty, no Stealth disadvantage.',                       fullDescription: 'No movement speed penalty, no Stealth disadvantage regardless of armor category. Engineered for minimal encumbrance.' },
  { id: 'magnetic-boots',    name: 'Magnetic Boots',    shortDescription: 'Walk on metallic surfaces regardless of gravity.',                 fullDescription: 'Walk on metallic surfaces regardless of gravity. Advantage on checks to resist being pushed, pulled, or knocked prone on metallic surfaces.' },
  { id: 'auto-medica',       name: 'Auto-Medica',       shortDescription: 'Auto-heal 1d8+prof when below half HP (1/long rest).',             fullDescription: 'Contains automated medical system. Once per long rest, when you drop below half HP, automatically regain 1d8 + proficiency bonus HP. No action required.' },
]

// ─── Armor Tier Definitions ───────────────────────────────────────────────────

export interface ArmorTierDef {
  tier: ItemTier
  color: string
  bonusAC: number
  damageResistances: number
  hasTraitSlot: boolean
}

export const armorTierDefinitions: ArmorTierDef[] = [
  { tier: 'standard',       color: 'white',  bonusAC: 0, damageResistances: 0, hasTraitSlot: false },
  { tier: 'master-crafted', color: 'green',  bonusAC: 1, damageResistances: 0, hasTraitSlot: false },
  { tier: 'artificer',      color: 'purple', bonusAC: 1, damageResistances: 1, hasTraitSlot: true  },
  { tier: 'relic',          color: 'gold',   bonusAC: 1, damageResistances: 2, hasTraitSlot: true  },
  { tier: 'heroic',         color: 'red',    bonusAC: 2, damageResistances: 3, hasTraitSlot: true  },
]

// ─── Light Armor ─────────────────────────────────────────────────────────────

export const lightArmor: Item[] = [
  {
    id: 'armored-bodyglove',
    name: 'Armored Bodyglove',
    type: 'armor',
    tier: 'standard',
    armorType: 'light',
    armorClass: 11,
    stealthDisadvantage: false,
    properties: ['Lightweight'],
    description: 'A tight-fitting bodyglove with reinforced panels. Undetectable under clothing.',
    cost: '15 Thrones',
    weight: 4,
    equipmentSlot: 'body',
    tags: ['light-armor', 'common'],
  },
  {
    id: 'flak-jacket',
    name: 'Flak Jacket',
    type: 'armor',
    tier: 'standard',
    armorType: 'light',
    armorClass: 12,
    stealthDisadvantage: false,
    properties: [],
    description: 'Ceramic plates sewn into a heavy vest. Standard issue for PDF troopers and militia.',
    cost: '20 Thrones',
    weight: 8,
    equipmentSlot: 'body',
    tags: ['light-armor', 'common'],
  },
  {
    id: 'mesh-armor',
    name: 'Mesh Armor',
    type: 'armor',
    tier: 'standard',
    armorType: 'light',
    armorClass: 12,
    stealthDisadvantage: false,
    properties: ['Lightweight'],
    description: 'Interlocked rings of hardened wire woven into a flexible suit. Popular with Inquisitorial agents.',
    cost: '50 Thrones',
    weight: 6,
    equipmentSlot: 'body',
    tags: ['light-armor', 'uncommon'],
  },
  {
    id: 'xeno-mesh',
    name: 'Xeno-Mesh',
    type: 'armor',
    tier: 'standard',
    armorType: 'light',
    armorClass: 13,
    stealthDisadvantage: false,
    properties: ['Lightweight'],
    description: 'Mesh armor woven from xenos-derived materials. Lighter and stronger than standard mesh.',
    cost: '200 Thrones',
    weight: 4,
    equipmentSlot: 'body',
    tags: ['light-armor', 'rare'],
  },
  {
    id: 'synskin',
    name: 'Synskin',
    type: 'armor',
    tier: 'standard',
    armorType: 'light',
    armorClass: 11,
    stealthDisadvantage: false,
    properties: ['Lightweight', 'Sealed'],
    description: 'A skin-tight synth-fiber suit. Advantage on Stealth. Sealed against toxins (2 hr air supply).',
    cost: '250 Thrones',
    weight: 2,
    equipmentSlot: 'body',
    tags: ['light-armor', 'rare'],
  },
]

// ─── Medium Armor ─────────────────────────────────────────────────────────────

export const mediumArmor: Item[] = [
  {
    id: 'flak-armor-full',
    name: 'Flak Armor (Full)',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 13,
    maxDexBonus: 2,
    stealthDisadvantage: false,
    properties: [],
    description: 'Full-body flak armor covering torso, limbs, and groin. Standard Imperial Guard issue.',
    cost: '30 Thrones',
    weight: 15,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'common'],
  },
  {
    id: 'guard-flak',
    name: 'Guard Flak',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 14,
    maxDexBonus: 2,
    stealthDisadvantage: false,
    properties: [],
    description: 'Upgraded flak armor with thicker plates and improved fit. Issued to veteran Guardsmen.',
    cost: '50 Thrones',
    weight: 18,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'common'],
  },
  {
    id: 'enforcer-carapace',
    name: 'Enforcer Carapace',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 14,
    maxDexBonus: 2,
    stealthDisadvantage: true,
    properties: ['Intimidating'],
    description: 'Bulky carapace plating used by Arbites enforcers. Intimidating in appearance.',
    cost: '100 Thrones',
    weight: 20,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'uncommon'],
  },
  {
    id: 'stormcoat',
    name: 'Stormcoat',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 15,
    maxDexBonus: 2,
    strengthRequirement: 12,
    stealthDisadvantage: true,
    properties: ['Ablative'],
    description: 'A heavy armored coat with ablative layers. First hit each combat reduced by 1d6.',
    cost: '150 Thrones',
    weight: 25,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'uncommon'],
  },
  {
    id: 'feudal-plate',
    name: 'Feudal Plate',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 15,
    maxDexBonus: 2,
    strengthRequirement: 13,
    stealthDisadvantage: true,
    properties: ['Cumbersome'],
    description: 'Plate armor from a feudal world. Effective but slow.',
    cost: '75 Thrones',
    weight: 30,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'common'],
  },
  {
    id: 'tempestus-carapace',
    name: 'Tempestus Carapace',
    type: 'armor',
    tier: 'standard',
    armorType: 'medium',
    armorClass: 15,
    maxDexBonus: 2,
    strengthRequirement: 12,
    stealthDisadvantage: false,
    properties: ['Lightweight', 'Ablative'],
    description: 'Advanced carapace used by Tempestus Scions. Lightweight and ablative.',
    cost: '300 Thrones',
    weight: 18,
    equipmentSlot: 'body',
    tags: ['medium-armor', 'rare'],
  },
]

// ─── Heavy Armor ──────────────────────────────────────────────────────────────

export const heavyArmor: Item[] = [
  {
    id: 'carapace-armor',
    name: 'Carapace Armor',
    type: 'armor',
    tier: 'standard',
    armorType: 'heavy',
    armorClass: 16,
    maxDexBonus: 0,
    strengthRequirement: 13,
    stealthDisadvantage: true,
    properties: ['Bulky'],
    description: 'Full carapace plating covering the entire body. Standard Arbites and Stormtrooper armor.',
    cost: '200 Thrones',
    weight: 40,
    equipmentSlot: 'body',
    tags: ['heavy-armor', 'uncommon'],
  },
  {
    id: 'storm-trooper-carapace',
    name: 'Storm Trooper Carapace',
    type: 'armor',
    tier: 'standard',
    armorType: 'heavy',
    armorClass: 17,
    maxDexBonus: 0,
    strengthRequirement: 14,
    stealthDisadvantage: true,
    properties: ['Bulky', 'Sealed'],
    description: 'Full-sealed carapace used by elite Storm Troopers. Provides environmental protection.',
    cost: '500 Thrones',
    weight: 45,
    equipmentSlot: 'body',
    tags: ['heavy-armor', 'rare'],
  },
  {
    id: 'arbites-suppression-armor',
    name: 'Arbites Suppression Armor',
    type: 'armor',
    tier: 'standard',
    armorType: 'heavy',
    armorClass: 17,
    maxDexBonus: 0,
    strengthRequirement: 14,
    stealthDisadvantage: true,
    properties: ['Bulky', 'Intimidating', 'Reinforced'],
    description: 'Heavy suppression armor worn by Arbites riot control units. Crits treated as normal hits.',
    cost: '600 Thrones',
    weight: 50,
    equipmentSlot: 'body',
    tags: ['heavy-armor', 'rare'],
  },
  {
    id: 'power-armor',
    name: 'Power Armor',
    type: 'armor',
    tier: 'standard',
    armorType: 'heavy',
    armorClass: 18,
    maxDexBonus: 0,
    strengthRequirement: 16,
    stealthDisadvantage: true,
    properties: ['Powered', 'Sealed', 'Bulky', 'Reinforced'],
    description: 'Powered armor with full environmental sealing. Removes STR requirement while active. If power fails, wearer is restrained until removed (10 min).',
    cost: '2000 Thrones',
    weight: 65,
    equipmentSlot: 'body',
    tags: ['heavy-armor', 'very-rare'],
  },
  {
    id: 'terminator-armor',
    name: 'Terminator Armor',
    type: 'armor',
    tier: 'standard',
    armorType: 'heavy',
    armorClass: 19,
    maxDexBonus: 0,
    strengthRequirement: 18,
    stealthDisadvantage: true,
    properties: ['Powered', 'Sealed', 'Bulky', 'Reinforced', 'Cumbersome'],
    description: 'The pinnacle of personal armor. Completely impenetrable to most weapons. If power fails, wearer is restrained.',
    cost: 'Priceless',
    weight: 100,
    equipmentSlot: 'body',
    tags: ['heavy-armor', 'legendary'],
  },
]

// ─── Shields ──────────────────────────────────────────────────────────────────

export const shields: Item[] = [
  {
    id: 'combat-shield',
    name: 'Combat Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 1,
    properties: [],
    description: '+1 AC. Strapped to the forearm, leaving the hand free for simple tasks.',
    cost: '10 Thrones',
    weight: 3,
    equipmentSlot: 'shield',
    tags: ['shield', 'common'],
  },
  {
    id: 'kite-shield',
    name: 'Kite Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 2,
    properties: [],
    description: '+2 AC. Standard military kite shield.',
    cost: '15 Thrones',
    weight: 6,
    equipmentSlot: 'shield',
    tags: ['shield', 'common'],
  },
  {
    id: 'suppression-shield',
    name: 'Suppression Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 2,
    properties: ['Intimidating'],
    description: '+2 AC. Transparent plasteel. Advantage on saves vs Blast weapons while wielding.',
    cost: '50 Thrones',
    weight: 8,
    equipmentSlot: 'shield',
    tags: ['shield', 'uncommon'],
  },
  {
    id: 'tower-shield',
    name: 'Tower Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 3,
    properties: ['Cumbersome'],
    description: '+3 AC. Provides three-quarters cover when planted (action). Speed −5 ft. Cannot use two-handed weapon while wielding.',
    cost: '75 Thrones',
    weight: 15,
    equipmentSlot: 'shield',
    tags: ['shield', 'uncommon'],
  },
  {
    id: 'storm-shield',
    name: 'Storm Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 2,
    properties: ['Powered'],
    itemAbilities: [
      { name: 'Energy Field', description: 'Advantage on all DEX saving throws while wielding.', actionType: 'passive' },
    ],
    description: '+2 AC. Built-in energy field generator grants advantage on DEX saves.',
    cost: '300 Thrones',
    weight: 6,
    equipmentSlot: 'shield',
    tags: ['shield', 'rare'],
  },
  {
    id: 'boarding-shield',
    name: 'Boarding Shield',
    type: 'armor',
    tier: 'standard',
    armorType: 'shield',
    bonusAC: 2,
    properties: [],
    itemAbilities: [
      { name: 'Integrated Laspistol', description: 'Built-in laspistol (1d6 energy, 30/120 ft). Can attack with the shield as a bonus action.', actionType: 'bonus-action' },
    ],
    description: '+2 AC. Built-in laspistol (1d6, 30/120 ft). Can attack with shield as bonus action.',
    cost: '200 Thrones',
    weight: 10,
    equipmentSlot: 'shield',
    tags: ['shield', 'rare'],
  },
]

// ─── Helmets ──────────────────────────────────────────────────────────────────

export const helmets: Item[] = [
  {
    id: 'flak-helmet',
    name: 'Flak Helmet',
    type: 'gear',
    tier: 'standard',
    bonusAC: 0,
    properties: [],
    itemAbilities: [
      { name: 'Head Protection', description: 'Advantage on saves vs critical hits to the head (GM discretion).', actionType: 'passive' },
    ],
    description: 'Basic flak helmet. Advantage on saves vs head crits.',
    cost: '5 Thrones',
    weight: 2,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'common'],
  },
  {
    id: 'guard-helm',
    name: 'Guard Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: [],
    itemAbilities: [
      { name: 'Integrated Vox-Bead', description: 'Short-range communication (1 mile).', actionType: 'passive' },
    ],
    description: '+1 AC. Integrated vox-bead (1 mile range).',
    cost: '15 Thrones',
    weight: 3,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'common'],
  },
  {
    id: 'enforcer-helm',
    name: 'Enforcer Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: [],
    itemAbilities: [
      { name: 'Photo-Visor', description: 'Immune to being blinded by flash grenades.', actionType: 'passive' },
    ],
    description: '+1 AC. Photo-visor grants immunity to flash blinding. Intimidating appearance.',
    cost: '50 Thrones',
    weight: 4,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'uncommon'],
  },
  {
    id: 'rebreather-helm',
    name: 'Rebreather Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 0,
    properties: ['Sealed'],
    itemAbilities: [
      { name: 'Sealed Air', description: 'Sealed air supply (4 hours). Immune to inhaled toxins and gas weapons. Can operate in vacuum.', actionType: 'passive' },
    ],
    description: 'Rebreather helmet. Sealed (4 hr air), immune to inhaled toxins, can operate in vacuum.',
    cost: '20 Thrones',
    weight: 3,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'common'],
  },
  {
    id: 'carapace-helm',
    name: 'Carapace Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: ['Reinforced'],
    itemAbilities: [
      { name: 'Reinforced Shell', description: 'Critical hits to the head are treated as normal hits. Sealed if paired with Sealed armor.', actionType: 'passive' },
    ],
    description: '+1 AC. Reinforced — crits to the head treated as normal hits.',
    cost: '75 Thrones',
    weight: 5,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'uncommon'],
  },
  {
    id: 'targeteer-helm',
    name: 'Targeteer Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 0,
    properties: [],
    itemAbilities: [
      { name: 'Targeting Reticle', description: '+1 to ranged attack rolls. Darkvision 60 ft.', actionType: 'passive' },
    ],
    description: 'Integrated targeting reticle: +1 to ranged attack rolls. Darkvision 60 ft.',
    cost: '100 Thrones',
    weight: 3,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'uncommon'],
  },
  {
    id: 'sororitas-war-helm',
    name: 'Sororitas War Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: ['Sealed'],
    itemAbilities: [
      { name: 'Sacred Wards', description: 'Advantage on saves vs fear and psychic effects.', actionType: 'passive' },
      { name: 'Integrated Vox', description: 'Built-in encrypted vox communication.', actionType: 'passive' },
    ],
    description: '+1 AC. Sealed. Advantage on saves vs fear and psychic effects.',
    cost: '200 Thrones',
    weight: 4,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'rare'],
  },
  {
    id: 'storm-trooper-helm',
    name: 'Storm Trooper Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: ['Sealed'],
    itemAbilities: [
      { name: 'Enhanced Optics', description: 'Sealed. Darkvision 120 ft. Integrated auspex: can\'t be surprised. +1 to initiative.', actionType: 'passive' },
    ],
    description: '+1 AC. Sealed. Darkvision 120 ft. Cannot be surprised. +1 to initiative.',
    cost: '250 Thrones',
    weight: 5,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'rare'],
  },
  {
    id: 'skull-mask',
    name: 'Skull Mask',
    type: 'gear',
    tier: 'standard',
    bonusAC: 0,
    properties: [],
    itemAbilities: [
      { name: 'Death Visage', description: 'Advantage on Intimidation checks. Enemies that can see you have −1 to morale saves.', actionType: 'passive' },
    ],
    description: 'Skull-faced mask. Advantage on Intimidation. Enemies take −1 to morale saves.',
    cost: '10 Thrones',
    weight: 1,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'common'],
  },
  {
    id: 'void-helm',
    name: 'Void Helm',
    type: 'gear',
    tier: 'standard',
    bonusAC: 1,
    properties: ['Sealed'],
    itemAbilities: [
      { name: 'Void Shielding', description: 'Sealed (8 hours). Radiation shielding. HUD: advantage on Navigation and Investigation in void environments.', actionType: 'passive' },
    ],
    description: '+1 AC. Sealed (8 hr). Radiation shielding. HUD grants advantage on void navigation.',
    cost: '150 Thrones',
    weight: 4,
    equipmentSlot: 'helmet',
    tags: ['helmet', 'rare'],
  },
]

// ─── Cloaks ───────────────────────────────────────────────────────────────────

export const cloaks: Item[] = [
  {
    id: 'camo-cloak',
    name: 'Camo Cloak',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Natural Camouflage', description: 'Advantage on Stealth in natural environments (forests, ruins, deserts). Provides half cover when prone.', actionType: 'passive' },
    ],
    description: 'Advantage on Stealth in natural terrain. Half cover when prone.',
    cost: '15 Thrones',
    weight: 3,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'common'],
  },
  {
    id: 'cameleoline-cloak',
    name: 'Cameleoline Cloak',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Active Camouflage', description: 'Advantage on ALL Stealth checks. When prone and not moving, effectively invisible (Perception DC 18 to spot).', actionType: 'passive' },
    ],
    description: 'Advantage on all Stealth. When prone and motionless, effectively invisible (DC 18 to spot).',
    cost: '200 Thrones',
    weight: 2,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'rare'],
  },
  {
    id: 'stormcloak',
    name: 'Stormcloak',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Cold Resistance', description: 'Resistance to cold damage. Advantage on saves vs extreme weather.', actionType: 'passive' },
    ],
    description: 'Resistance to cold damage. Advantage on saves vs extreme weather.',
    cost: '20 Thrones',
    weight: 5,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'common'],
  },
  {
    id: 'refractor-cape',
    name: 'Refractor Cape',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Refractor Field', description: 'Once per short rest, when hit by an attack, reduce damage by 2d6.', actionType: 'reaction', usesPerRest: 'short', usesCount: '1' },
    ],
    description: 'Built-in refractor field. Once per short rest, reduce incoming damage by 2d6.',
    cost: '300 Thrones',
    weight: 3,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'rare'],
  },
  {
    id: 'rosarius-cloak',
    name: 'Rosarius Cloak',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Blessed Wards', description: '+1 to all saving throws. Advantage on saves vs psychic damage and corruption.', actionType: 'passive' },
    ],
    description: '+1 to all saves. Advantage on saves vs psychic damage and corruption.',
    cost: '500 Thrones',
    weight: 2,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'very-rare'],
  },
  {
    id: 'deadfall-cloak',
    name: 'Deadfall Cloak',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Shadow Movement', description: 'Advantage on Stealth in darkness or dim light. While in darkness, immune to detection by hearing.', actionType: 'passive' },
    ],
    description: 'Advantage on Stealth in darkness/dim light. Immune to sound-based detection in darkness.',
    cost: '75 Thrones',
    weight: 2,
    equipmentSlot: 'cloak-backpack',
    tags: ['cloak', 'uncommon'],
  },
]

// ─── Backpacks ────────────────────────────────────────────────────────────────

export const backpacks: Item[] = [
  {
    id: 'military-pack',
    name: 'Military Pack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Field Kit', description: 'Carrying capacity +50 lb. Contains bedroll, mess kit, rations (5 days), waterskin, rope (50 ft), flashlight.', actionType: 'passive' },
    ],
    description: 'Standard military pack. +50 lb carrying capacity. Contains standard field supplies.',
    cost: '10 Thrones',
    weight: 5,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'common'],
  },
  {
    id: 'medicae-backpack',
    name: 'Medicae Backpack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Field Medic', description: '+2 to Medicine checks. Can stabilize a creature at 0 HP as a bonus action.', actionType: 'passive' },
    ],
    description: '+2 to Medicine checks. Stabilize at 0 HP as a bonus action.',
    cost: '75 Thrones',
    weight: 8,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'uncommon'],
  },
  {
    id: 'vox-pack',
    name: 'Vox-Pack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Long-Range Vox', description: 'Long-range vox-caster (50 mile range). Can contact orbital vessels. Encryption capability.', actionType: 'passive' },
    ],
    description: 'Long-range vox (50 miles). Can contact orbital ships. Encrypted comms.',
    cost: '50 Thrones',
    weight: 10,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'uncommon'],
  },
  {
    id: 'ammunition-pack',
    name: 'Ammunition Pack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Extra Ammo', description: 'Doubles starting ammunition. When you would run out of ammo, roll d6: on 4+, find one more magazine/pack.', actionType: 'passive' },
    ],
    description: 'Doubles starting ammo for all weapons. On empty, roll d6: 4+ finds one more magazine.',
    cost: '20 Thrones',
    weight: 10,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'common'],
  },
  {
    id: 'tech-pack',
    name: 'Tech-Pack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Mechanic\'s Kit', description: '+2 to Technology and repair checks. Can jury-rig broken equipment (DC 15 INT check, lasts 1 hour).', actionType: 'passive' },
    ],
    description: 'Contains mechanic\'s tools, spare parts, data-slate. +2 Technology/repair. Jury-rig broken gear (DC 15 INT, 1 hr).',
    cost: '60 Thrones',
    weight: 12,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'uncommon'],
  },
  {
    id: 'demolitions-pack',
    name: 'Demolitions Pack',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Demo Expert', description: '+2 to checks involving explosives. Can set charges as a bonus action. Contains 4 det charges, detonators, tripwire.', actionType: 'passive' },
    ],
    description: 'Contains 4 det charges, detonators, tripwire. +2 explosives. Set charges as bonus action.',
    cost: '100 Thrones',
    weight: 15,
    equipmentSlot: 'cloak-backpack',
    tags: ['backpack', 'uncommon'],
  },
]

// ─── Accessories ──────────────────────────────────────────────────────────────

export const accessories: Item[] = [
  // Defensive
  {
    id: 'refractor-field',
    name: 'Refractor Field',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Refractor Field', description: 'Once per short rest, when hit by a ranged attack, negate the damage entirely. Does not work against melee.', actionType: 'reaction', usesPerRest: 'short', usesCount: '1' },
    ],
    description: 'Once per short rest, negate all damage from one ranged attack.',
    cost: '300 Thrones',
    weight: 1,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'rare'],
  },
  {
    id: 'hexagrammic-wards',
    name: 'Hexagrammic Wards',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Warding Symbols', description: 'Advantage on saves vs psychic powers, warp effects, and daemonic abilities. +2 to saves vs possession.', actionType: 'passive' },
    ],
    description: 'Advantage on saves vs psychic/warp/daemonic. +2 vs possession.',
    cost: '250 Thrones',
    weight: 0,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'rare'],
  },
  {
    id: 'iron-halo',
    name: 'Iron Halo',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Iron Halo', description: 'Once per long rest, activate as a reaction when hit: gain resistance to ALL damage until the start of your next turn.', actionType: 'reaction', usesPerRest: 'long', usesCount: '1' },
    ],
    description: 'Once per long rest, gain resistance to ALL damage until start of your next turn.',
    cost: '800 Thrones',
    weight: 1,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'very-rare'],
  },
  {
    id: 'null-rod',
    name: 'Null Rod',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Null Field', description: 'Advantage on saves vs psychic powers. Psykers within 10 ft subtract 2 from spell attack rolls and save DCs.', actionType: 'passive' },
    ],
    description: 'Advantage vs psychic. Psykers within 10 ft have −2 to spell attacks and DCs.',
    cost: '500 Thrones',
    weight: 2,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'very-rare'],
  },
  {
    id: 'combat-webbing',
    name: 'Combat Webbing',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Quick Draw', description: '+2 to initiative rolls. Can draw or stow one additional item per turn as a free action. Advantage on checks to avoid being disarmed.', actionType: 'passive' },
    ],
    description: '+2 initiative. Draw extra item free each turn. Advantage vs disarm.',
    cost: '15 Thrones',
    weight: 2,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
  // Utility
  {
    id: 'vox-bead',
    name: 'Vox-Bead',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Short-Range Comms', description: 'Short-range communication (1 mile). Hands-free. Whisper and still be heard by allies with vox-beads.', actionType: 'passive' },
    ],
    description: 'Hands-free vox comms (1 mile range). Whisper-capable.',
    cost: '5 Thrones',
    weight: 0,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
  {
    id: 'photo-visor',
    name: 'Photo-Visor',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Enhanced Vision', description: 'Immune to being blinded by flash effects. Darkvision 30 ft.', actionType: 'passive' },
    ],
    description: 'Immune to flash blindness. Darkvision 30 ft.',
    cost: '15 Thrones',
    weight: 1,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
  {
    id: 'magnoculars',
    name: 'Magnoculars',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Long-Range Vision', description: 'See clearly up to 1 mile. +2 to Perception checks involving sight at long range.', actionType: 'passive' },
    ],
    description: 'See clearly up to 1 mile. +2 Perception at long range.',
    cost: '10 Thrones',
    weight: 1,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
  {
    id: 'grapnel-launcher',
    name: 'Grapnel Launcher',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Grappling Hook', description: '30 ft grappling hook launcher. Climb speed equal to half movement speed. Can be used as a bonus action.', actionType: 'bonus-action' },
    ],
    description: '30 ft grapnel. Climb at half speed. Launch as bonus action.',
    cost: '25 Thrones',
    weight: 3,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'uncommon'],
  },
  {
    id: 'auspex-scanner',
    name: 'Auspex Scanner',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Life-Sign Detection', description: 'As an action, detect all living creatures within 60 ft through walls and cover. Reveals invisible creatures.', actionType: 'action' },
    ],
    description: 'Detect all living creatures within 60 ft through walls. Reveals invisible creatures.',
    cost: '75 Thrones',
    weight: 2,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'uncommon'],
  },
  {
    id: 'micro-bead-translator',
    name: 'Micro-Bead Translator',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Real-Time Translation', description: 'Real-time translation of up to 3 pre-programmed languages. Advantage on Persuasion and Deception across language barriers.', actionType: 'passive' },
    ],
    description: 'Translates up to 3 languages. Advantage on Persuasion/Deception across language barriers.',
    cost: '50 Thrones',
    weight: 0,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'uncommon'],
  },
  {
    id: 'purity-seal',
    name: 'Purity Seal',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Emperor\'s Favour', description: '+1 to saves vs fear and Corruption effects. Visible symbol of the Emperor\'s favour.', actionType: 'passive' },
    ],
    description: '+1 to saves vs fear and Corruption. Symbol of the Emperor\'s favour.',
    cost: '5 Thrones',
    weight: 0,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
  {
    id: 'chrono',
    name: 'Chrono',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Timekeeping', description: 'Always know the exact time. +1 to initiative. Can set alarms and timers.', actionType: 'passive' },
    ],
    description: 'Always know the exact time. +1 to initiative.',
    cost: '10 Thrones',
    weight: 0,
    equipmentSlot: 'accessory',
    tags: ['accessory', 'common'],
  },
]

// ─── Clothing ─────────────────────────────────────────────────────────────────

export const clothing: Item[] = [
  // Noble & Social
  {
    id: 'nobles-robes',
    name: 'Noble\'s Robes',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Noble Status', description: 'Advantage on Persuasion and Deception in social settings among the upper class. Marks you as a person of status.', actionType: 'passive' },
    ],
    description: 'Advantage on Persuasion/Deception with upper class. Marks you as a person of status.',
    cost: '50 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'ecclesiarchy-vestments',
    name: 'Ecclesiarchy Vestments',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Religious Authority', description: 'Advantage on Persuasion with Imperial citizens and the faithful. Can invoke religious authority (Persuasion DC 12) for minor requests.', actionType: 'passive' },
    ],
    description: 'Advantage on Persuasion with Imperial faithful. Invoke religious authority (DC 12) for minor requests.',
    cost: '30 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'administratum-uniform',
    name: 'Administratum Uniform',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Bureaucratic Access', description: 'Advantage on Investigation and Persuasion when navigating bureaucracy. Access to administrative buildings without question.', actionType: 'passive' },
    ],
    description: 'Advantage on Investigation/Persuasion in bureaucracy. Access to admin buildings unquestioned.',
    cost: '20 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'merchants-finery',
    name: 'Merchant\'s Finery',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Trader\'s Guile', description: 'Advantage on Persuasion checks involving trade, negotiation, and pricing.', actionType: 'passive' },
    ],
    description: 'Advantage on Persuasion involving trade, negotiation, and pricing.',
    cost: '40 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'rogue-trader-regalia',
    name: 'Rogue Trader Regalia',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Warrant of Trade', description: 'Advantage on Intimidation and Persuasion in any setting. The Warrant of Trade opens doors across the Imperium.', actionType: 'passive' },
    ],
    description: 'Advantage on Intimidation and Persuasion in any setting. Opens doors across the Imperium.',
    cost: '200 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'rare'],
  },
  // Environmental
  {
    id: 'void-suit',
    name: 'Void Suit',
    type: 'gear',
    tier: 'standard',
    armorClass: 10,
    maxDexBonus: 0,
    itemAbilities: [
      { name: 'Void Protection', description: 'Sealed environment suit (8 hours oxygen). Protection against vacuum, radiation, and toxic atmospheres. Speed −10 ft.', actionType: 'passive' },
    ],
    description: 'AC 10. Sealed (8 hr). Protects vs vacuum, radiation, toxic atmospheres. Speed −10 ft.',
    cost: '100 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'uncommon'],
  },
  {
    id: 'hazmat-suit',
    name: 'Hazmat Suit',
    type: 'gear',
    tier: 'standard',
    armorClass: 10,
    maxDexBonus: 0,
    itemAbilities: [
      { name: 'Hazardous Protection', description: 'Resistance to poison and acid damage. Immune to contact toxins and diseases. Speed −5 ft.', actionType: 'passive' },
    ],
    description: 'AC 10. Resist poison and acid. Immune to contact toxins and diseases. Speed −5 ft.',
    cost: '75 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'uncommon'],
  },
  {
    id: 'cold-weather-gear',
    name: 'Cold Weather Gear',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Cold Insulation', description: 'Resistance to cold damage. Advantage on saves vs extreme cold and hypothermia.', actionType: 'passive' },
    ],
    description: 'Resistance to cold. Advantage vs extreme cold and hypothermia.',
    cost: '20 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'desert-survival-gear',
    name: 'Desert Survival Gear',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Heat Insulation', description: 'Advantage on saves vs extreme heat and dehydration. Water consumption halved.', actionType: 'passive' },
    ],
    description: 'Advantage vs extreme heat and dehydration. Water consumption halved.',
    cost: '15 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'radiation-suit',
    name: 'Radiation Suit',
    type: 'gear',
    tier: 'standard',
    armorClass: 10,
    maxDexBonus: 0,
    itemAbilities: [
      { name: 'Rad Shielding', description: 'Resistance to radiant damage from radiation sources. Advantage on saves vs radiation sickness.', actionType: 'passive' },
    ],
    description: 'AC 10. Resistance to radiant (radiation). Advantage vs radiation sickness.',
    cost: '80 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'uncommon'],
  },
  // Stealth & Infiltration
  {
    id: 'bodyglove-infiltration',
    name: 'Bodyglove (Infiltration)',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Infiltrator\'s Weave', description: 'Advantage on Stealth checks. Can be worn under other clothing without detection.', actionType: 'passive' },
    ],
    description: 'Advantage on Stealth. Worn under clothing without detection.',
    cost: '50 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'uncommon'],
  },
  {
    id: 'disguise-robes',
    name: 'Disguise Robes',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Local Disguise', description: '+2 to Disguise checks. Pass as local civilian in any hive, agri-world, or shrine world.', actionType: 'passive' },
    ],
    description: '+2 to Disguise. Pass as local civilian on most worlds.',
    cost: '10 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'common'],
  },
  {
    id: 'servo-skull-relay',
    name: 'Servo-Skull Relay',
    type: 'gear',
    tier: 'standard',
    itemAbilities: [
      { name: 'Skull Scout', description: 'A servo-skull follows you and relays visual/audio data. Can scout up to 500 ft ahead. Worn on a belt harness.', actionType: 'passive' },
    ],
    description: 'A servo-skull scouts up to 500 ft ahead, relaying visual/audio data.',
    cost: '150 Thrones',
    equipmentSlot: 'clothing',
    tags: ['clothing', 'rare'],
  },
]

// ─── Armor Sets ───────────────────────────────────────────────────────────────

export const armorSets: ArmorSet[] = [
  {
    id: 'cadian-shock-trooper-kit',
    name: 'Cadian Shock Trooper Kit',
    description: 'Guard Flak + Guard Helm + Military Pack + Vox-Bead. Standard Cadian veteran loadout.',
    pieces: ['guard-flak', 'guard-helm', 'military-pack', 'vox-bead'],
    setBonus: {
      name: 'Disciplined Fire',
      description: 'When you take the Attack action with a ranged weapon, add +1 to each damage roll. You and allies wearing any piece within 30 ft gain +1 to initiative.',
      actionType: 'passive',
    },
    totalCost: '80 Thrones',
    tags: ['common', 'cadian'],
  },
  {
    id: 'arbites-riot-control-suit',
    name: 'Arbites Riot Control Suit',
    description: 'Enforcer Carapace + Enforcer Helm + Suppression Shield + Combat Webbing.',
    pieces: ['enforcer-carapace', 'enforcer-helm', 'suppression-shield', 'combat-webbing'],
    setBonus: {
      name: 'Law and Order',
      description: 'Once per short rest, as an action, slam your shield and shout a command. All hostile creatures within 20 ft make WIS save (DC 13) or frightened for 1 round and drop one held item. Civilians automatically fail.',
      actionType: 'action',
      usesPerRest: 'short',
      usesCount: '1',
    },
    totalCost: '215 Thrones',
    tags: ['uncommon', 'arbites'],
  },
  {
    id: 'tempestus-scion-battle-gear',
    name: 'Tempestus Scion Battle Gear',
    description: 'Tempestus Carapace + Storm Trooper Helm + Ammunition Pack + Combat Webbing.',
    pieces: ['tempestus-carapace', 'storm-trooper-helm', 'ammunition-pack', 'combat-webbing'],
    setBonus: {
      name: 'Precision Drop',
      description: 'When you roll initiative, you can choose to act last in the first round. If you do, all attacks you make during that first round have advantage and deal an extra 1d6 damage.',
      actionType: 'passive',
    },
    totalCost: '585 Thrones',
    tags: ['rare', 'tempestus'],
  },
  {
    id: 'catachan-jungle-fighter-kit',
    name: 'Catachan Jungle Fighter Kit',
    description: 'Flak Jacket + Camo Cloak + Vox-Bead.',
    pieces: ['flak-jacket', 'camo-cloak', 'vox-bead'],
    setBonus: {
      name: 'Jungle Ghost',
      description: 'In natural terrain, enemies have disadvantage on Perception checks to find you. You can Hide as a bonus action. You ignore difficult terrain in forests, jungles, and swamps.',
      actionType: 'passive',
    },
    totalCost: '42 Thrones',
    tags: ['common', 'catachan'],
  },
  {
    id: 'sisters-of-battle-war-plate',
    name: 'Sisters of Battle War Plate',
    description: 'Carapace Armor + Sororitas War Helm + Rosarius Cloak + Purity Seal.',
    pieces: ['carapace-armor', 'sororitas-war-helm', 'rosarius-cloak', 'purity-seal'],
    setBonus: {
      name: 'Shield of Faith',
      description: 'Once per long rest, as a reaction when you or an ally within 15 ft takes damage, halve the damage and grant 2d8 temp HP. While all pieces worn, melee attacks deal +1d4 radiant vs daemons and undead.',
      actionType: 'reaction',
      usesPerRest: 'long',
      usesCount: '1',
    },
    totalCost: '905 Thrones',
    tags: ['rare', 'sororitas'],
  },
  {
    id: 'void-pirates-rig',
    name: 'Void Pirate\'s Rig',
    description: 'Mesh Armor + Void Helm + Grapnel Launcher.',
    pieces: ['mesh-armor', 'void-helm', 'grapnel-launcher'],
    setBonus: {
      name: 'Zero-G Fighter',
      description: 'No disadvantage from fighting in zero or low gravity. Walk on walls and ceilings on metallic surfaces. When you grapple a creature, use your reaction to redirect momentum — throw the grappled creature 10 ft.',
      actionType: 'passive',
    },
    totalCost: '400 Thrones',
    tags: ['uncommon', 'void'],
  },
  {
    id: 'inquisitorial-storm-kit',
    name: 'Inquisitorial Storm Kit',
    description: 'Storm Trooper Carapace + Storm Trooper Helm + Refractor Cape + Hexagrammic Wards.',
    pieces: ['storm-trooper-carapace', 'storm-trooper-helm', 'refractor-cape', 'hexagrammic-wards'],
    setBonus: {
      name: 'The Emperor\'s Inquisition',
      description: 'Advantage on Intimidation against all creatures. Once per long rest, when you would be reduced to 0 HP, instead drop to 1 HP and gain resistance to all damage until end of your next turn.',
      actionType: 'special',
      usesPerRest: 'long',
      usesCount: '1',
    },
    totalCost: '1300 Thrones',
    tags: ['very-rare', 'inquisition'],
  },
]

// ─── All Items Export ─────────────────────────────────────────────────────────

export const allArmorItems: Item[] = [
  ...lightArmor,
  ...mediumArmor,
  ...heavyArmor,
  ...shields,
  ...helmets,
  ...cloaks,
  ...backpacks,
  ...accessories,
  ...clothing,
]
