import type { Item } from '../../../types/module'

// ─── Legacy Items (converted to Thrones) ────────────────────────────────────

const legacyConsumables: Item[] = [
  {
    id: 'healing-potion',
    name: 'Healing Potion',
    type: 'consumable',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Restores 2d4+2 hit points when consumed.',
    weight: 0.5,
    cost: '5 Thrones',
    description: 'Restores 2d4+2 hit points when consumed.',
    tags: ['consumable', 'healing'],
  },
  {
    id: 'antitoxin',
    name: 'Antitoxin',
    type: 'consumable',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Grants advantage on saving throws against poison for 1 hour.',
    weight: 0,
    cost: '5 Thrones',
    description: 'Grants advantage on saving throws against poison for 1 hour.',
    tags: ['consumable', 'utility'],
  },
  {
    id: 'torch',
    name: 'Torch',
    type: 'consumable',
    consumableActionType: 'free',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Burns for 1 hour, shedding bright light in a 20-foot radius and dim light for an additional 20 feet.',
    weight: 1,
    cost: '1 Throne',
    description: 'Burns for 1 hour, shedding bright light in a 20-foot radius and dim light for an additional 20 feet.',
    tags: ['consumable', 'light'],
  },
]

// ─── Combat Consumables (Stimulants) ─────────────────────────────────────────

const stimmConsumables: Item[] = [
  {
    id: 'stimm',
    name: 'Stimm',
    type: 'consumable',
    description: 'A cheap combat stimulant. Quick burst of energy.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: '+1d4 temporary HP and advantage on next attack roll. Duration: 1 round.',
    cost: '5 Thrones',
    weight: 0.1,
  },
  {
    id: 'combat-stimm',
    name: 'Combat Stimm',
    type: 'consumable',
    description: 'A more potent stimulant favored by Imperial Guard sergeants.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: '+2d6 temporary HP and +2 to attack rolls for 1 minute.',
    postUseSaveDC: 12,
    postUseSaveAbility: 'constitution',
    postUseFailureEffect: '1 level of exhaustion',
    cost: '10 Thrones',
    weight: 0.1,
  },
  {
    id: 'frenzon',
    name: 'Frenzon',
    type: 'consumable',
    description: 'A combat drug favored by Khorne cultists and Imperial penal legions. Pushes you past sanity.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Advantage on all melee attacks and Strength checks for 1 minute. You cannot retreat or take non-attack actions.',
    postUseSaveDC: 14,
    postUseSaveAbility: 'constitution',
    postUseFailureEffect: '1 level of exhaustion',
    addictionDC: 12,
    cost: '25 Thrones',
    weight: 0.1,
  },
  {
    id: 'slaught',
    name: 'Slaught',
    type: 'consumable',
    description: 'A reflex-enhancing stimulant. Time slows. So do you, eventually.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: '+3 to initiative, advantage on Dexterity saves, extra reaction per round for 1 minute.',
    postUseSaveDC: 13,
    postUseSaveAbility: 'constitution',
    postUseFailureEffect: '1 level of exhaustion',
    addictionDC: 13,
    cost: '30 Thrones',
    weight: 0.1,
  },
  {
    id: 'spur',
    name: '\'Spur',
    type: 'consumable',
    description: 'Pure speed. Pure consequences.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Movement speed doubled for 1 minute. Dash as bonus action.',
    postUseSaveDC: 12,
    postUseSaveAbility: 'constitution',
    postUseFailureEffect: 'Speed halved for 1 hour',
    cost: '15 Thrones',
    weight: 0.1,
  },
  {
    id: 'satrophine',
    name: 'Satrophine',
    type: 'consumable',
    description: 'A psychic-suppressant euphoric. Mostly used by commissars and inquisitors.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Immune to frightened condition for 1 hour. +2 to Wisdom saves vs psychic effects. Mild euphoria.',
    cost: '20 Thrones',
    weight: 0.1,
  },
  {
    id: 'kalma',
    name: 'Kalma',
    type: 'consumable',
    description: 'A pain suppressant. The wound is still there. You just can\'t feel it.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Immune to pain. You don\'t feel damage for 10 minutes. You still take damage normally but don\'t know how much.',
    addictionDC: 11,
    cost: '10 Thrones',
    weight: 0.1,
  },
  {
    id: 'obscura',
    name: 'Obscura',
    type: 'consumable',
    description: 'An illegal recreational narcotic. Possession is a capital offense in most jurisdictions.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Advantage on all Charisma checks for 1 hour. Disadvantage on all combat rolls (you\'re high).',
    addictionDC: 14,
    cost: '15 Thrones',
    weight: 0.1,
  },
  {
    id: 'recaf-strong',
    name: 'Recaf (Strong)',
    type: 'consumable',
    description: 'Imperial-grade caffeine concentrate. Space coffee. Mostly legal.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Removes 1 level of exhaustion. +1 to Perception checks for 4 hours.',
    cost: '1 Throne',
    weight: 0.2,
  },
  {
    id: 'psychon',
    name: 'Psychon',
    type: 'consumable',
    description: 'A psyker-only stimulant. Burns the soul to fuel the mind.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Reduce Warp Bar by 3. Next psychic power\'s save DC increased by +2.',
    postUseSaveDC: 14,
    postUseSaveAbility: 'constitution',
    postUseFailureEffect: '2d6 psychic damage',
    addictionDC: 13,
    restrictedToClasses: ['psyker'],
    cost: '50 Thrones',
    weight: 0.1,
  },
]

// ─── Combat Consumables (Field Medical) ──────────────────────────────────────

const fieldMedicalConsumables: Item[] = [
  {
    id: 'med-pack-basic',
    name: 'Med-Pack (Basic)',
    type: 'consumable',
    description: 'Standard issue field medical kit. Stims, gauze, antiseptic.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Heal 1d8+2 HP.',
    cost: '10 Thrones',
    weight: 0.5,
  },
  {
    id: 'med-pack-advanced',
    name: 'Med-Pack (Advanced)',
    type: 'consumable',
    tier: 'master-crafted',
    description: 'Improved field medical kit with broad-spectrum compounds.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Heal 2d8+4 HP. Removes the poisoned condition.',
    cost: '30 Thrones',
    weight: 0.5,
  },
  {
    id: 'med-pack-superior',
    name: 'Med-Pack (Superior)',
    type: 'consumable',
    tier: 'artificer',
    description: 'Mechanicus-blessed medical kit. Used by chirurgeons and Apothecaries.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Heal 4d8+8 HP. Removes the poisoned, blinded, or deafened condition.',
    cost: '75 Thrones',
    weight: 0.5,
  },
  {
    id: 'trauma-kit',
    name: 'Trauma Kit',
    type: 'consumable',
    description: 'Emergency stabilization kit. Adrenaline, blood coagulant, defibrillators.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Stabilize a creature at 0 HP automatically (no check needed). Grants 1 HP.',
    cost: '15 Thrones',
    weight: 1,
  },
  {
    id: 'blood-coagulant',
    name: 'Blood Coagulant',
    type: 'consumable',
    description: 'Injected anticoagulant counter-agent. Stops bleeding fast.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Stop all bleeding effects immediately. Grants resistance to slashing damage for 1 minute.',
    cost: '20 Thrones',
    weight: 0.1,
  },
  {
    id: 'detox',
    name: 'De-Tox',
    type: 'consumable',
    description: 'Universal detox compound. Pulls poison and chems out fast.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Immediately end one poison or drug effect (including addiction withdrawal).',
    cost: '15 Thrones',
    weight: 0.1,
  },
  {
    id: 'synth-skin-spray',
    name: 'Synth-Skin Spray',
    type: 'consumable',
    description: 'Aerosolized synthetic skin sealant. Cosmetic — the spray is skin-colored.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Seal a wound. Grants 1d4 temporary HP and prevents infection from the wound.',
    cost: '5 Thrones',
    weight: 0.1,
  },
  {
    id: 'pain-suppressant',
    name: 'Pain Suppressant',
    type: 'consumable',
    description: 'A milder kalma analog. Take the edge off.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Ignore effects of one level of exhaustion for 4 hours. The exhaustion is still there; you just don\'t feel it.',
    cost: '5 Thrones',
    weight: 0.1,
  },
]

// ─── Combat Consumables (Combat Utility) ─────────────────────────────────────

const combatUtilityConsumables: Item[] = [
  {
    id: 'smoke-canister',
    name: 'Smoke Canister',
    type: 'consumable',
    description: 'Standard issue smoke grenade. Cover, signal, distraction.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '60 feet',
    consumableAreaOfEffect: '15-foot radius sphere',
    consumableEffect: 'Creates a heavily obscured area for 1 minute. Deployable (throw or plant).',
    cost: '5 Thrones',
    weight: 1,
  },
  {
    id: 'flare',
    name: 'Flare',
    type: 'consumable',
    description: 'Signal flare. Visible for miles.',
    consumableActionType: 'bonus-action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Illuminates 60 ft radius bright light, 60 ft dim for 10 minutes. Can be fired as a signal visible for miles.',
    cost: '2 Thrones',
    weight: 0.5,
  },
  {
    id: 'glow-rod',
    name: 'Glow Rod',
    type: 'consumable',
    description: 'Chemical light stick. No battery needed. Reliable.',
    consumableActionType: 'free',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Bright light 30 ft, dim 30 ft for 8 hours.',
    cost: '1 Throne',
    weight: 0.5,
  },
  {
    id: 'flash-charge',
    name: 'Flash Charge',
    type: 'consumable',
    description: 'A reactive blinding device. Detonates on motion.',
    consumableActionType: 'reaction',
    consumableCharges: 1,
    consumableRange: '5 feet',
    consumableAreaOfEffect: '5-foot radius',
    consumableSaveDC: '13',
    consumableSaveAbility: 'constitution',
    consumableEffect: 'When a creature moves within 5 ft, detonate as a reaction. CON save DC 13 or blinded for 1 round.',
    cost: '15 Thrones',
    weight: 0.5,
  },
  {
    id: 'stasis-grenade',
    name: 'Stasis Grenade',
    type: 'consumable',
    tier: 'artificer',
    description: 'Archeotech device. Freezes a target outside of time itself.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '60 feet',
    consumableAreaOfEffect: '5-foot radius',
    consumableSaveDC: '14',
    consumableSaveAbility: 'wisdom',
    consumableEffect: 'WIS save DC 14 or frozen in time for 1 round (incapacitated, invulnerable, immovable).',
    cost: '50 Thrones',
    weight: 1,
  },
  {
    id: 'promethium-canister',
    name: 'Promethium Canister',
    type: 'consumable',
    description: 'Standard fuel canister for flamers, vehicles, and incendiaries.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '20 feet',
    consumableAreaOfEffect: '5-foot blast',
    consumableSaveDC: '12',
    consumableSaveAbility: 'dexterity',
    consumableDamage: '2d6',
    consumableDamageType: 'fire',
    consumableEffect: 'Fuel for flamers (6 shots when used as ammunition). Can be thrown as improvised incendiary: 2d6 fire damage in 5-foot blast, DEX save DC 12 for half.',
    tags: ['flamer-fuel'],
    cost: '10 Thrones',
    weight: 3,
  },
  {
    id: 'acid-vial',
    name: 'Acid Vial',
    type: 'consumable',
    description: 'Industrial-grade acid in a fragile glass vial. Eats through metal.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '20 feet',
    consumableDamage: '2d6',
    consumableDamageType: 'acid',
    consumableEffect: 'Throw at target. 2d6 acid damage on hit. Dissolves locks, hinges, and thin barriers in 1 minute.',
    cost: '15 Thrones',
    weight: 0.5,
  },
  {
    id: 'mag-clamp-mine',
    name: 'Mag-Clamp Mine (Anti-Personnel)',
    type: 'consumable',
    description: 'Magnetic proximity mine. Plants on metal. Triggers on motion.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableAreaOfEffect: '5-foot radius',
    consumableSaveDC: '14',
    consumableSaveAbility: 'dexterity',
    consumableDamage: '3d8',
    consumableDamageType: 'piercing',
    consumableEffect: 'Plant on metallic surface. Proximity trigger (5 ft). 3d8 piercing damage, DEX save DC 14 for half.',
    cost: '30 Thrones',
    weight: 2,
  },
  {
    id: 'targeter-dart',
    name: 'Targeter Dart',
    type: 'consumable',
    description: 'A tracking dart fired from any ranged weapon. Marks the target for the squad.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '60 feet',
    consumableEffect: 'Fire from any ranged weapon. No damage. Target is marked for 1 hour — all attacks against them ignore cover bonuses.',
    cost: '20 Thrones',
    weight: 0,
  },
  {
    id: 'null-grenade',
    name: 'Null Grenade',
    type: 'consumable',
    tier: 'artificer',
    description: 'A psyker-suppression grenade. Crystallizes the Warp around its detonation point.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: '60 feet',
    consumableAreaOfEffect: '15-foot radius',
    consumableEffect: 'All psychic effects in the area are dispelled. Psykers in the area cannot use powers for 1 round.',
    cost: '75 Thrones',
    weight: 1,
  },
]

// ─── Medical Supplies ────────────────────────────────────────────────────────

const medicalSupplies: Item[] = [
  {
    id: 'antidote-general',
    name: 'Antidote (General)',
    type: 'consumable',
    description: 'Broad-spectrum poison neutralizer. Hit-or-miss against specific toxins.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Neutralize one poison affecting a creature. Medicine check DC 12. If check fails, the antidote is still consumed but has no effect.',
    cost: '10 Thrones',
    weight: 0.1,
  },
  {
    id: 'antidote-specific',
    name: 'Antidote (Specific)',
    type: 'consumable',
    description: 'A custom-tailored antidote prepared with a Poisoner\'s Kit. Must match the poison.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Auto-neutralize one specific poison (must match). No check needed. Must be prepared in advance with Poisoner\'s Kit.',
    cost: '25 Thrones',
    weight: 0.1,
  },
  {
    id: 'broad-spectrum-antibiotic',
    name: 'Broad-Spectrum Antibiotic',
    type: 'consumable',
    description: 'Standard Imperial antibiotic. Treats most non-magical infections.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Cure one non-magical disease over 24 hours. Medicine check DC 13 to administer correctly.',
    cost: '15 Thrones',
    weight: 0.1,
  },
  {
    id: 'anti-rad-compound',
    name: 'Anti-Rad Compound',
    type: 'consumable',
    description: 'Radiation neutralizer. Standard issue on hot worlds.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Reduce radiation sickness by one stage. Grants advantage on saves vs radiation for 24 hours.',
    cost: '20 Thrones',
    weight: 0.1,
  },
  {
    id: 'counterseptic',
    name: 'Counterseptic',
    type: 'consumable',
    description: 'Wound-cleaning antiseptic. Standard medic kit component.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Prevent infection in an open wound. If applied within 1 hour of injury, the wound heals cleanly. Without it, GM may impose infection complications.',
    cost: '3 Thrones',
    weight: 0.1,
  },
  {
    id: 'rejuvenat-dose',
    name: 'Rejuvenat Dose',
    type: 'consumable',
    tier: 'artificer',
    description: 'Reverse-ageing compound. Used by Imperial nobility to extend their lives. Side effects can be lethal.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Self',
    consumableEffect: 'Reduces biological age by 1d10 years. Multiple doses in a year require CON save DC 15 or suffer 2d6 necrotic damage (body rejection).',
    cost: '500 Thrones',
    weight: 0.1,
  },
  {
    id: 'psychic-suppressant',
    name: 'Psychic Suppressant',
    type: 'consumable',
    description: 'Anti-Warp drug. Used by sanctioned psykers and rogue psyker hunters.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Suppresses psychic abilities for 8 hours. Warp Bar resets to 0 while suppressed.',
    cost: '50 Thrones',
    weight: 0.1,
  },
  {
    id: 'anti-venom-xenos',
    name: 'Anti-Venom (Xenos)',
    type: 'consumable',
    description: 'Anti-venom calibrated for xenos toxins. Tyranid bio-weapons, Eldar wraithbone poisons, etc.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Neutralize xenos-origin poisons and toxins. Broader spectrum than standard antidotes. Medicine check DC 14.',
    cost: '40 Thrones',
    weight: 0.1,
  },
  {
    id: 'surgical-kit',
    name: 'Surgical Kit',
    type: 'consumable',
    description: 'Field surgery kit. Scalpels, forceps, sutures, stims.',
    consumableActionType: 'action',
    consumableCharges: 10,
    consumableRange: 'Touch',
    consumableEffect: 'Required for field surgery (setting bones, removing projectiles, closing deep wounds). +2 to Medicine checks for surgery.',
    cost: '50 Thrones',
    weight: 3,
  },
  {
    id: 'augmetic-repair-kit',
    name: 'Augmetic Repair Kit',
    type: 'consumable',
    description: 'Mechanicus-issued tools for cybernetic maintenance.',
    consumableActionType: 'action',
    consumableCharges: 5,
    consumableRange: 'Touch',
    consumableEffect: 'Repair damaged augmetics and cybernetics. Technology check DC 13. Restores function to one damaged augment.',
    cost: '75 Thrones',
    weight: 5,
  },
  {
    id: 'bone-knitting-compound',
    name: 'Bone-Knitting Compound',
    type: 'consumable',
    description: 'Injectable bone regeneration matrix.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Injected into fracture site. Broken bone heals in 8 hours instead of weeks. Medicine check DC 12.',
    cost: '30 Thrones',
    weight: 0.2,
  },
  {
    id: 'synthetic-blood',
    name: 'Synthetic Blood (1 unit)',
    type: 'consumable',
    description: 'A unit of universal-donor synthetic blood. Used in transfusions.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Transfusion replaces lost blood. Restores 2d8 HP when administered during a short rest. Requires medkit.',
    cost: '25 Thrones',
    weight: 2,
  },
  {
    id: 'skin-graft-kit',
    name: 'Skin Graft Kit',
    type: 'consumable',
    description: 'Surface burn and wound treatment kit.',
    consumableActionType: 'action',
    consumableCharges: 3,
    consumableRange: 'Touch',
    consumableEffect: 'Repair severe burns and surface wounds. Heals 1d6 HP and removes the scarred condition (if your system uses one).',
    cost: '40 Thrones',
    weight: 1,
  },
  {
    id: 'nerve-stapler',
    name: 'Nerve Stapler',
    type: 'consumable',
    description: 'Specialized surgical tool for reconnecting severed nerves.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Reconnect severed nerves. Required to restore function to a paralyzed or severed limb (along with surgery).',
    cost: '100 Thrones',
    weight: 0.5,
  },
  {
    id: 'organ-preservation-flask',
    name: 'Organ Preservation Flask',
    type: 'gear',
    description: 'A reusable flask that keeps a harvested organ viable for 72 hours. Required for transplant surgery.',
    cost: '75 Thrones',
    weight: 2,
  },
  {
    id: 'emergency-augmetic-limb',
    name: 'Emergency Augmetic Limb',
    type: 'consumable',
    tier: 'artificer',
    description: 'A basic prosthetic — hand, arm, leg, or eye. Functional but crude.',
    consumableActionType: 'action',
    consumableCharges: 1,
    consumableRange: 'Touch',
    consumableEffect: 'Functional but crude: -1 to checks involving the limb until properly fitted (requires 3 days and a tech-priest). Better than nothing.',
    cost: '200 Thrones',
    weight: 5,
  },
]

// ─── Export ──────────────────────────────────────────────────────────────────

export const allConsumables: Item[] = [
  ...legacyConsumables,
  ...stimmConsumables,
  ...fieldMedicalConsumables,
  ...combatUtilityConsumables,
  ...medicalSupplies,
]
