import type { Item } from '../../../types/module'

// ─── Body Armor (Light) ───────────────────────────────────────────────────────

const shadowweaveSilk: Item = {
  id: 'shadowweave-silk',
  name: 'Shadowweave Silk',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 12,
  equipmentSlot: 'body',
  bonusAC: 1,
  properties: ['Silent'],
  lore: 'A bodyglove woven from Catachan silk-spider thread by a Callidus Temple artificer. The weave dampens movement sound to near-nothing and provides light protection without restricting the wearer\'s legendary flexibility.',
  description: 'Base: Bodyglove. AC 12 + DEX. +1 AC (named). Advantage on Stealth checks while worn.',
  cost: 'Rare',
  weight: 3,
  tags: ['armor', 'named', 'light', 'stealth', 'callidus'],
}

const scintillanMerchantCoat: Item = {
  id: 'scintillan-merchant-coat',
  name: 'Scintillan Merchant\'s Coat',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 11,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A long coat worn by a Scintilla merchant lord who survived three assassination attempts. The interior is lined with woven ablative plating disguised as quilted fabric. Tailored to look entirely mundane.',
  description: 'Base: Flak Coat. AC 11 + DEX. +1 AC (named). Does not appear as armour on casual inspection (Perception DC 15 to detect).',
  cost: 'Rare',
  weight: 5,
  tags: ['armor', 'named', 'light', 'concealed', 'scintilla'],
}

const arbitesConcealedVest: Item = {
  id: 'arbites-concealed-vest',
  name: 'Arbites Concealed Vest',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 13,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A personal commission from Proctor-Senioris Valdane, built by an Adeptus Arbites armourer who added an additional ablative layer after the Proctor survived a close call in the underhive. The armourer was proud of the work. So was the Proctor.',
  description: 'Base: Carapace Vest (light). AC 13 + DEX. +1 AC (named). Resistance to the first instance of piercing damage in each combat.',
  cost: 'Rare',
  weight: 8,
  tags: ['armor', 'named', 'light', 'arbites'],
}

const tanithScoutLeathers: Item = {
  id: 'tanith-scout-leathers',
  name: 'Tanith Scout Leathers',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 12,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Leatherwork by a Tanith First-and-Only scout, cured from Nalwood-tree bark-leather and hand-stitched with resin-coated thread that repels moisture and noise. The Ghosts live and die by their ability to disappear.',
  description: 'Base: Scout Leathers. AC 12 + DEX. +1 AC (named). Advantage on Stealth in wilderness or rubble terrain. Ignore difficult terrain from undergrowth.',
  cost: 'Rare',
  weight: 4,
  tags: ['armor', 'named', 'light', 'tanith', 'scout'],
}

const kriegTrenchCoat: Item = {
  id: 'krieg-trench-coat',
  name: 'Krieg Trench Coat',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 12,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Standard Krieg field-gear elevated to individual excellence — the trench coat of a Death Korps sergeant who survived the Siege of Vraks. Treated against chemical agents, lined with additional blast-weave at the torso. Smells faintly of Zyklon-1 neutraliser.',
  description: 'Base: Flak Coat. AC 12 + DEX. +1 AC (named). Advantage on CON saves against chemical/gas weapons. Cannot be frightened while wearing.',
  cost: 'Rare',
  weight: 6,
  tags: ['armor', 'named', 'light', 'krieg', 'gas'],
}

const vostroyaOfficerJacket: Item = {
  id: 'vostroyan-officer-jacket',
  name: 'Vostroyan Officer\'s Jacket',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 11,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A First-Born officer\'s ceremonial jacket with hidden inner-layer ablative lining. The outer embroidery is a declaration of lineage; the inner weave is a declaration of survival. Both matter on Vostroyan worlds.',
  description: 'Base: Dress Uniform/Flak. AC 11 + DEX. +1 AC (named). Advantage on Persuasion and Intimidation vs Imperial military personnel while worn. Does not appear as combat armour.',
  cost: 'Rare',
  weight: 3,
  tags: ['armor', 'named', 'light', 'vostroyan', 'officer'],
}

const exploratorsBodyskin: Item = {
  id: 'explorators-bodyskin',
  name: 'Explorator\'s Bodyskin',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 12,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A full-body skinsuit created by a Rogue Trader\'s personal armourer for extended void and wilderness operations. Contains micro-sensors for atmospheric analysis and a reactive ablative layer that stiffens on impact. Worn under regular clothing.',
  description: 'Base: Bodyglove. AC 12 + DEX. +1 AC (named). Automatically detects hostile atmospheres. Can be worn under clothing without detection.',
  cost: 'Rare',
  weight: 2,
  tags: ['armor', 'named', 'light', 'explorator', 'rogue-trader'],
}

const hiveGangLeaders: Item = {
  id: 'hive-gang-leader-coat',
  name: 'The Gang Leader\'s Coat',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 11,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A coat that has passed between Necromundan gang leaders for three generations. Each added their own modifications. The current version includes layered ablative panels, knife-proof synthetic silk lining, and a very fashionable collar.',
  description: 'Base: Gang Leathers. AC 11 + DEX. +1 AC (named). Advantage on Intimidation in underhive settings. Enemies must make WIS DC 12 or be visually distracted by the coat\'s intimidating presence.',
  cost: 'Rare',
  weight: 4,
  tags: ['armor', 'named', 'light', 'necromunda', 'gang'],
}

// ─── Body Armor (Medium) ──────────────────────────────────────────────────────

const guardianFlakElit: Item = {
  id: 'guardian-flak-elite',
  name: 'Guardian\'s Flak Elite',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 14,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Standard Guard flak armour elevated by an Armourer-Sergeant who spent twenty years perfecting the fit and balance. Every plate aligned precisely, straps calibrated to the individual wearer, ablative layers doubled at the torso.',
  description: 'Base: Guard Flak. AC 14 + DEX (max 2). +1 AC (named). On the first hit each combat, the damage is reduced by 3.',
  cost: 'Rare',
  weight: 18,
  tags: ['armor', 'named', 'medium', 'guard', 'flak'],
}

const kasrkinCombatArmour: Item = {
  id: 'kasrkin-combat-armour',
  name: 'Kasrkin Combat Armour',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 15,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Built for the Kasrkin — Cadia\'s elite stormtroopers — this armour combines advanced composite materials with a thermoptic camouflage underlayer that activates when stationary. The Kasrkin survived Cadia\'s fall. Some of this armour did too.',
  description: 'Base: Carapace Armour. AC 15 + DEX (max 2). +1 AC (named). When stationary for your full turn, gain advantage on Stealth checks until you move.',
  cost: 'Rare',
  weight: 20,
  tags: ['armor', 'named', 'medium', 'kasrkin', 'cadia'],
}

const mordianIronGuardPlate: Item = {
  id: 'mordian-iron-guard-plate',
  name: 'Mordian Iron Guard Plate',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 14,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'The parade-perfect armour of the Mordian Iron Guard. Every surface polished to mirror brightness, every fit adjusted by the regimental armourer. The Mordians believe that fighting well begins with looking right. Their casualty rates suggest they are correct.',
  description: 'Base: Guard Flak. AC 14 + DEX (max 2). +1 AC (named). Cannot be surprised when alert. Allies within 10 ft have advantage on Morale saves.',
  cost: 'Rare',
  weight: 19,
  tags: ['armor', 'named', 'medium', 'mordian', 'iron-guard'],
}

const tallarnDesertMail: Item = {
  id: 'tallarn-desert-mail',
  name: 'Tallarn Desert Mail',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 13,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Lightweight ablative mail worn by Tallarn Raiders, optimised for desert operations. The outer layer is heat-reflective ceramic; the inner is moisture-wicking synth-cotton. It has been adapted to dissipate the heat of nearby explosions.',
  description: 'Base: Carapace Vest + mail. AC 13 + DEX (max 2). +1 AC (named). Resistance to fire damage. No penalty to Stealth in desert/sandy terrain.',
  cost: 'Rare',
  weight: 15,
  tags: ['armor', 'named', 'medium', 'tallarn', 'desert'],
}

const armageddonSteelSuit: Item = {
  id: 'armageddon-steel-suit',
  name: 'Armageddon Steel Suit',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 14,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Forged in the manufactorums of Armageddon between the First and Second Wars. Built heavier than standard flak with reinforced knees and shoulders for urban warfare. The Armageddon Steel Legion calls this "the suit that keeps you fighting until you can\'t."',
  description: 'Base: Guard Flak (reinforced). AC 14 + DEX (max 2). +1 AC (named). Advantage on STR saves vs knockdown/knockback. +2 to Athletics checks.',
  cost: 'Rare',
  weight: 22,
  tags: ['armor', 'named', 'medium', 'armageddon', 'steel-legion'],
}

const penitentFlakSuit: Item = {
  id: 'penitent-flak-suit',
  name: 'Penitent\'s Flak Suit',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 14,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Modified from standard Guard flak by a Death Cult Penitent who inscribed litanies of suffering across every plate. The armour has absorbed decades of self-flagellation. It seems to harden in response to pain, as if the litanies are more than decoration.',
  description: 'Base: Guard Flak. AC 14 + DEX (max 2). +1 AC (named). When you take damage, your next attack roll has advantage (resets each turn).',
  cost: 'Rare',
  weight: 18,
  tags: ['armor', 'named', 'medium', 'penitent', 'death-cult'],
}

// ─── Body Armor (Heavy) ───────────────────────────────────────────────────────

const kriegSiegeArmour: Item = {
  id: 'krieg-siege-armour',
  name: 'Krieg Siege Armour',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'heavy',
  armorClass: 17,
  maxDexBonus: 0,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'Full siege plate built for the Death Korps of Krieg\'s assault engineers. Thicker at the front than standard carapace, with reinforced knee and elbow strikes. The Korps do not retreat. The armour was designed with this in mind.',
  description: 'Base: Siege Carapace. AC 17. +1 AC (named). Cannot be pushed or knocked prone against your will. Resistance to blast damage.',
  cost: 'Rare',
  weight: 55,
  tags: ['armor', 'named', 'heavy', 'krieg', 'siege'],
}

const magosFieldPlate: Item = {
  id: 'magos-field-plate',
  name: 'Magos Field Plate',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'heavy',
  armorClass: 16,
  maxDexBonus: 0,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'A Mechanicus Magos\' personal field armour integrating cogitator-assisted threat assessment, blessed alloy plating, and a micro-mechadendrite socket at the shoulder. Built for long campaigns in hostile forge-worlds.',
  description: 'Base: Magos Armour. AC 16. +1 AC (named). Cannot be surprised by mechanical or technological threats. Advantage on checks to interface with technology.',
  cost: 'Rare',
  weight: 50,
  tags: ['armor', 'named', 'heavy', 'mechanicus', 'magos'],
}

const catachanJungleHarness: Item = {
  id: 'catachan-jungle-harness',
  name: 'Catachan Jungle Harness',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'medium',
  armorClass: 14,
  maxDexBonus: 2,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'The Catachans live and die in the deadliest jungles in the galaxy. Their armour reflects this: maximum coverage, minimum encumbrance, with built-in toxin-absorption layers harvested from the very beasts trying to kill them.',
  description: 'Base: Guard Flak/Jungle Harness. AC 14 + DEX (max 2). +1 AC (named). Advantage on CON saves vs poison/toxin. Cannot be paralysed by natural toxins.',
  cost: 'Rare',
  weight: 17,
  tags: ['armor', 'named', 'medium', 'catachan', 'jungle'],
}

const fenrisianBearPelt: Item = {
  id: 'fenrisian-bear-pelt',
  name: 'Fenrisian Bear Pelt',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'light',
  armorClass: 13,
  equipmentSlot: 'body',
  bonusAC: 1,
  lore: 'The cured hide of a Fenrisian Bear, one of the apex predators of the death world. A Space Wolves skjald blessed the hide before presentation to a warrior who had proven themselves in the trial against the beast. The hide retains a supernatural resilience.',
  description: 'Base: Heavy Furs/Hide. AC 13 + DEX. +1 AC (named). Advantage on CON saves vs cold. While below half HP, gain +2 AC from instinctive defensive reflexes.',
  cost: 'Rare',
  weight: 10,
  tags: ['armor', 'named', 'light', 'fenris', 'space-wolves'],
}

// ─── Shields ──────────────────────────────────────────────────────────────────

const aegisShieldMC: Item = {
  id: 'aegis-shield-mc',
  name: 'Aegis Combat Shield',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'shield',
  equipmentSlot: 'shield',
  bonusAC: 3,
  lore: 'A combat shield carried by a Cadian officer through the Fall of Cadia. One side bears the Cadian Gate; the other has been scratched with the names of fallen soldiers. The shield absorbed fifteen direct hits. The officer survived.',
  description: 'Shield. +3 AC (MC +1). When an adjacent ally is hit by an attack, you may use your reaction to interpose the shield and reduce that damage by 1d6.',
  cost: 'Rare',
  weight: 6,
  tags: ['shield', 'named', 'cadia'],
}

const dueling_buckler: Item = {
  id: 'dueling-buckler-mc',
  name: 'Scintillan Duelist\'s Buckler',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'shield',
  equipmentSlot: 'shield',
  bonusAC: 3,
  properties: ['Finesse'],
  lore: 'Crafted for the duelling schools of Scintilla where the buckler is considered an offensive as well as defensive weapon. The edge is razored; the boss is weighted for a punch. The duellist who carried it is long dead. The buckler remembers his technique.',
  description: 'Shield. +3 AC (MC +1). Can be used to make an unarmed strike attack (1d4 bludgeoning) as a bonus action.',
  cost: 'Rare',
  weight: 3,
  tags: ['shield', 'named', 'scintilla', 'dueling'],
}

const ironGuardBulwark: Item = {
  id: 'iron-guard-bulwark',
  name: 'Iron Guard Bulwark',
  type: 'armor',
  tier: 'master-crafted',
  isNamed: true,
  armorType: 'shield',
  equipmentSlot: 'shield',
  bonusAC: 3,
  lore: 'An Iron Guard parade shield elevated to battlefield use. Constructed from Mechanicus-blessed alloy with a mirror-polish finish. The Mordian Iron Guard believe a soldier who cannot present arms properly cannot fight properly. Empirical evidence is complicated.',
  description: 'Shield. +3 AC (MC +1). Allies who can see this shield have advantage on Morale saves.',
  cost: 'Rare',
  weight: 8,
  tags: ['shield', 'named', 'mordian', 'iron-guard'],
}

// ─── Helmets ──────────────────────────────────────────────────────────────────

const inquisitorialOpticHelm: Item = {
  id: 'inquisitorial-optic-helm',
  name: 'Inquisitorial Optic Helm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'helmet',
  bonusAC: 1,
  lore: 'A personalised Inquisitor\'s helm with a full-spectrum optic suite, cogitator-integrated threat assessment, and a rebreather mask sealed to Inquisitorial specification. The lenses are tinted red. The effect on witnesses is not coincidental.',
  description: 'Helm. +1 AC (named). See in darkness up to 60 ft. Advantage on Perception. Cannot be surprised.',
  cost: 'Rare',
  weight: 2,
  tags: ['helmet', 'named', 'inquisition', 'optics'],
}

const kriegGasHelm: Item = {
  id: 'krieg-gas-helm',
  name: 'Krieg Gas Mask Helm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'helmet',
  bonusAC: 1,
  lore: 'The distinctive death mask of the Death Korps, improved with triple-filtered rebreathers and blast-reinforced eye lenses. The Krieg wear it perpetually. It becomes their face, their identity, their psychological armour as much as physical.',
  description: 'Helm. +1 AC (named). Immune to gas and airborne toxins. Advantage on CON saves vs fear effects.',
  cost: 'Rare',
  weight: 2,
  tags: ['helmet', 'named', 'krieg', 'gas'],
}

const mechanicusSkullHelm: Item = {
  id: 'mechanicus-skull-helm',
  name: 'Mechanicus Skull Helm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'helmet',
  bonusAC: 1,
  lore: 'An armoury piece built by an Adeptus Mechanicus Enginseer with integrated data-uplinks, micro-auspex sensors, and an electoo interface at the temple. The skull motif is traditional. The electro-shock defence is not.',
  description: 'Helm. +1 AC (named). Integrated auspex (detect threats within 30 ft). Advantage on Arcana (tech) checks.',
  cost: 'Rare',
  weight: 3,
  tags: ['helmet', 'named', 'mechanicus', 'auspex'],
}

const arbitesRiotHelm: Item = {
  id: 'arbites-riot-helm',
  name: 'Arbites Riot Helm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'helmet',
  bonusAC: 1,
  lore: 'Standard Arbites riot gear elevated for an individual officer. Reinforced visor, integrated micro-vox, ident-scanner at the eyepiece, and a built-in amplifier for broadcasting commands across a riot zone.',
  description: 'Helm. +1 AC (named). Immune to blinding from flash/concussion weapons. Voice amplification: commands heard up to 100 ft clearly. Advantage on Intimidation vs mobs.',
  cost: 'Rare',
  weight: 2,
  tags: ['helmet', 'named', 'arbites', 'riot'],
}

const scoutAuspexHelm: Item = {
  id: 'scout-auspex-helm',
  name: 'Scout Auspex Helm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'helmet',
  bonusAC: 1,
  lore: 'A scout helm integrated with a miniaturised auspex unit for long-range reconnaissance. Used by an Astra Militarum forward observer who survived alone behind enemy lines for six weeks using only the information this helm provided.',
  description: 'Helm. +1 AC (named). Detect living creatures through walls within 20 ft. Advantage on Perception checks. +1 to ranged attack rolls when using integrated targeting.',
  cost: 'Rare',
  weight: 2,
  tags: ['helmet', 'named', 'scout', 'auspex'],
}

// ─── Cloaks ───────────────────────────────────────────────────────────────────

const thermalCloakDesert: Item = {
  id: 'thermal-cloak-desert',
  name: 'Tallarn Thermal Cloak',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'cloak-backpack',
  bonusAC: 1,
  lore: 'A specialist cloak developed for Tallarn Desert Raiders operating in high-heat environments. The fabric reflects thermal radiation, both incoming and outgoing, rendering the wearer invisible to thermal sensors and providing relief from desert sun.',
  description: 'Cloak. +1 AC (named). Invisible to thermal/infrared sensors. Resistance to environmental heat damage. Advantage on Stealth in desert environments.',
  cost: 'Rare',
  weight: 2,
  tags: ['cloak', 'named', 'tallarn', 'thermal'],
}

const catachanCamoCape: Item = {
  id: 'catachan-camo-cape',
  name: 'Catachan Camo Cape',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'cloak-backpack',
  bonusAC: 1,
  lore: 'Handmade from Catachan flora by a sniper who understood that survival in the Death World requires becoming part of it. The cape integrates living plant matter sealed in stasis weave. It adapts colour and texture to match its environment continuously.',
  description: 'Cloak. +1 AC (named). Advantage on Stealth in any natural environment. While prone and motionless, you cannot be spotted by vision alone at distances over 30 ft.',
  cost: 'Rare',
  weight: 3,
  tags: ['cloak', 'named', 'catachan', 'camouflage'],
}

const inquisitorsTravellingCloak: Item = {
  id: 'inquisitors-travelling-cloak',
  name: 'Inquisitor\'s Travelling Cloak',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'cloak-backpack',
  bonusAC: 1,
  lore: 'A grey cloak worn by a Ordo Xenos Inquisitor who travelled incognito across thirty systems. The exterior is drab and unremarkable. The interior is lined with a classified polymer that deflects low-calibre rounds. Both properties have saved his life equally.',
  description: 'Cloak. +1 AC (named). Resistance to the first instance of slashing or piercing damage per combat (inner lining). Advantage on Deception checks to pass as a non-Inquisitor.',
  cost: 'Rare',
  weight: 2,
  tags: ['cloak', 'named', 'inquisition', 'concealed'],
}

// ─── Accessories ─────────────────────────────────────────────────────────────

const blackstoneAmulet: Item = {
  id: 'blackstone-amulet',
  name: 'Blackstone Amulet',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'accessory',
  bonusAC: 1,
  lore: 'A pendant carved from a fragment of Blackstone Fortress material. The stone is naturally null, suppressing nearby warp phenomena. Psykers find it uncomfortable to be near. Everyone else finds it oddly calming.',
  description: 'Accessory. +1 AC (named). Advantage on saves vs psychic abilities and warp effects. Psychic abilities targeting you have their DC reduced by 2.',
  cost: 'Rare',
  weight: 0,
  tags: ['accessory', 'named', 'blackstone', 'anti-psychic'],
}

const refractorFieldBand: Item = {
  id: 'refractor-field-band',
  name: 'Refractor Field Band',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'accessory',
  bonusAC: 1,
  lore: 'A wrist-mounted refractor field generator of exceptional quality. The field distorts incoming energy weapons\' targeting lock. Used by an Inquisitorial Acolyte who faced plasma-armed cultists on seventeen separate occasions.',
  description: 'Accessory. +1 AC (named). When targeted by an energy weapon and hit, once per rest you may force the attacker to reroll (take lower result).',
  cost: 'Rare',
  weight: 1,
  tags: ['accessory', 'named', 'refractor', 'field'],
}

const scholamedSurgicalGauntlet: Item = {
  id: 'scholamed-surgical-gauntlet',
  name: 'Schola Medicae Surgical Gauntlet',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'accessory',
  bonusAC: 1,
  lore: 'A personalised medicae gauntlet with micro-injectors in the finger-tips and an integrated diagnostic cogitator at the wrist. Carried by a Schola Medicae Surgeon who treated over two thousand soldiers during the Macharian Crusade without a single preventable death.',
  description: 'Accessory. +1 AC (named). When you use Medicae to stabilise a dying creature, they also recover 1d6 HP. Advantage on Medicine checks.',
  cost: 'Rare',
  weight: 1,
  tags: ['accessory', 'named', 'medicae', 'surgeon'],
}

const ironHandsBionicArm: Item = {
  id: 'iron-hands-bionic-arm',
  name: 'Iron Hands Pattern Bionic Arm',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'accessory',
  bonusAC: 1,
  lore: 'A bionic arm replacement crafted in Iron Hands Chapter style — functional perfection over aesthetic concern. The arm contains a built-in wrist-blade and a magnetised grip that can hold weapons even when unconscious. The Iron Hands are proud. They always are.',
  description: 'Accessory. +1 AC (named). STR +2 for the replaced arm\'s purposes. Built-in wrist blade (1d4 slashing, retractable). Grip cannot be broken by external force.',
  cost: 'Rare',
  weight: 5,
  tags: ['accessory', 'named', 'bionic', 'iron-hands'],
}

const psy_dampener: Item = {
  id: 'psy-dampener-bracer',
  name: 'Psy-Dampener Bracer',
  type: 'gear',
  tier: 'master-crafted',
  isNamed: true,
  equipmentSlot: 'accessory',
  bonusAC: 1,
  lore: 'A bracer incorporating a Null-grade psy-dampening coil. Not enough to suppress psykers, but sufficient to make their abilities less reliable when targeting the wearer. Widely used by experienced Inquisitorial agents who have learned the hard way.',
  description: 'Accessory. +1 AC (named). Psychic abilities targeting you always require a roll (even if they are automatic). If the psyker rolls below 10, the ability fails entirely.',
  cost: 'Rare',
  weight: 1,
  tags: ['accessory', 'named', 'psy-dampener', 'inquisition'],
}

export const namedArmorMasterCrafted: Item[] = [
  shadowweaveSilk,
  scintillanMerchantCoat,
  arbitesConcealedVest,
  tanithScoutLeathers,
  kriegTrenchCoat,
  vostroyaOfficerJacket,
  exploratorsBodyskin,
  hiveGangLeaders,
  guardianFlakElit,
  kasrkinCombatArmour,
  mordianIronGuardPlate,
  tallarnDesertMail,
  armageddonSteelSuit,
  penitentFlakSuit,
  kriegSiegeArmour,
  magosFieldPlate,
  catachanJungleHarness,
  fenrisianBearPelt,
  aegisShieldMC,
  dueling_buckler,
  ironGuardBulwark,
  inquisitorialOpticHelm,
  kriegGasHelm,
  mechanicusSkullHelm,
  arbitesRiotHelm,
  scoutAuspexHelm,
  thermalCloakDesert,
  catachanCamoCape,
  inquisitorsTravellingCloak,
  blackstoneAmulet,
  refractorFieldBand,
  scholamedSurgicalGauntlet,
  ironHandsBionicArm,
  psy_dampener,
]
