import type { Item } from '../../../types/module'

// ─── Ranged ───────────────────────────────────────────────────────────────────

const godkiller: Item = {
  id: 'godkiller',
  name: 'Godkiller',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'heavy',
  rangeType: 'ranged',
  range: { normal: 120, long: 360 },
  damage: '6d6',
  damageType: 'heat',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Mounted', 'Melta'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Promethium Canister',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: God-Ending Beam',
      description: 'Once per day, Godkiller can be fired at maximum power. The beam deals 12d6 melta damage to the primary target (CON save DC 18 for half) and 6d6 to everything in a 5 ft wide, 120 ft line behind the target. This attack ignores all damage immunities.',
    },
  ],
  lore: 'The weapon that ended the Warlord Titan Maleficent Wrath during the Siege of Vraks. Wielded by Confessor Hieronymus who strode into the Titan\'s path alone. The Titan fired. He did not fall. He fired. The Titan did. The Mechanicus say this is impossible. Hieronymus says the Emperor willed it.',
  description: 'Base: Volkite Culverin/Melta-Cannon hybrid. +3 to attack rolls. +2d6 bonus damage. LEGENDARY God-Ending Beam (1/day): 12d6 melta vs target (CON DC 18 half), 6d6 in line, ignores immunities.',
  cost: 'Unique',
  weight: 30,
  tags: ['ranged', 'named', 'melta', 'heroic', 'vraks'],
}

const starFire: Item = {
  id: 'star-fire',
  name: 'Star Fire',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 90 },
  damage: '3d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'shot',
  ammoCapacity: 6,
  ammoName: 'Plasma Flask',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Solar Flare',
      description: 'Once per day, Star Fire can unleash a solar-intensity plasma discharge. All creatures within a 30 ft radius of the target take 4d6 energy damage (DEX save DC 18 for half). The area is bathed in blinding white light for 1 round — all creatures within 60 ft must succeed on a CON save DC 15 or be blinded. This attack cannot misfire.',
    },
  ],
  lore: 'A plasma gun whose plasma containment coil is built from a piece of a Necron power core. No one asked where the Inquisitor got it. The energy output is approximately 40% beyond any human plasma weapon. The Mechanicus is fascinated and horrified in equal measure.',
  description: 'Base: Plasma Gun. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Solar Flare (1/day): 30 ft radius 4d6 energy (DEX DC 18 half), blinding light 60 ft CON DC 15 or blinded.',
  cost: 'Unique',
  weight: 8,
  tags: ['ranged', 'named', 'plasma', 'heroic', 'necron'],
}

const ironVoice: Item = {
  id: 'iron-voice',
  name: 'Iron Voice',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'heavy',
  rangeType: 'ranged',
  range: { normal: 60, long: 240 },
  damage: '3d8',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Mounted', 'Rapid Fire (2)'],
  ammoType: 'belt',
  ammoCapacity: 40,
  ammoName: 'Belt Feed',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Voice of Command',
      description: 'Once per rest, Iron Voice\'s speakers broadcast a thunderous war-command. All allied creatures within 60 ft gain advantage on attack rolls for 1 minute and are immune to the frightened condition. Enemy creatures within 30 ft must make a WIS save DC 16 or be frightened for 1 round.',
    },
  ],
  lore: 'An assault cannon grafted with an Astropathic resonance amplifier — the weapon\'s machine spirit allows it to broadcast tactical commands across a battlefield. It was carried by General Andross at the Macharian Crusade\'s greatest victory.',
  description: 'Base: Assault Cannon. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Voice of Command (1/rest): allies 60 ft advantage + fear immunity; enemies 30 ft WIS DC 16 or frightened.',
  cost: 'Unique',
  weight: 22,
  tags: ['ranged', 'named', 'assault-cannon', 'heroic'],
}

const omnissiahsGaze: Item = {
  id: 'omnissiahs-gaze',
  name: "Omnissiah's Gaze",
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '2d10',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'shot',
  ammoCapacity: 5,
  ammoName: 'Power Cell',
  rechargeable: true,
  itemAbilities: [
    {
      name: 'LEGENDARY: Lascannon Overload',
      description: 'Once per day, the lascannon is overcharged to its absolute limit. The shot deals 4d10 energy damage (ignoring all resistance and immunity) to the target and 2d10 to everything in a 10 ft radius. Vehicles and armour hit by this take a permanent AC reduction of 2.',
    },
  ],
  lore: 'A Forge World Ryza lascannon of incomparable precision, gifted by the Archmagos to a champion who saved the Forge World from Ork invasion. The weapon\'s targeting system has been networked with the Forge World\'s planetary defence array — even from orbit, it fires true.',
  description: 'Base: Lascannon. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Lascannon Overload (1/day): 4d10 energy ignoring all immunity, 2d10 splash 10 ft radius, vehicles -2 AC permanent.',
  cost: 'Unique',
  weight: 15,
  tags: ['ranged', 'named', 'lascannon', 'heroic', 'ryza'],
}

const astartesForgiven: Item = {
  id: 'astartes-forgiven',
  name: 'The Forgiven',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 80, long: 240 },
  damage: '2d8',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Rapid Fire (1)'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Bolt Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Absolution Round',
      description: 'Once per combat, you may fire a single Absolution Round. The shot automatically hits and deals 5d8 + 2d6 piercing damage. If it kills the target, the target cannot be resurrected or reanimated by any means (warp, necron, or otherwise) for 1 year and 1 day.',
    },
  ],
  lore: 'A boltgun carried by a Dark Angels Interrogator-Chaplain. The magazine contains six black-tipped bolts that the Chaplain calls his "forgiveness" — absolute and terminal. Five have been used. One remains.',
  description: 'Base: Boltgun. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Absolution Round (1/combat): auto-hit 5d8+2d6, killed target cannot be resurrected for 1 year and 1 day.',
  cost: 'Unique',
  weight: 7,
  tags: ['ranged', 'named', 'bolt', 'heroic', 'dark-angels'],
}

const starlightShuriken: Item = {
  id: 'starlight-shuriken',
  name: 'Starlight',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'exotic',
  rangeType: 'ranged',
  range: { normal: 60, long: 180 },
  damage: '2d6',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Silent'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Disc Crystal',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Aspect of the Doom',
      description: 'Once per day, you may channel the spirit of the Asuryani death god. For 1 minute, all your attacks with Starlight deal an additional 3d6 psychic damage, and any creature reduced to 0 HP by Starlight is immediately and permanently slain (no death saves).',
    },
  ],
  lore: 'An Aeldari Shuriken Cannon of incomparable craftsmanship, the personal weapon of an Exarch of the Dark Reapers. It passed from Exarch to Exarch for four thousand years until the last Exarch gifted it to a human champion who had earned Aeldari respect. A thing that has not happened in living memory.',
  description: 'Base: Shuriken Cannon. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Aspect of the Doom (1/day): 1 minute all attacks +3d6 psychic; targets at 0 HP instantly and permanently slain.',
  cost: 'Unique',
  weight: 10,
  tags: ['ranged', 'named', 'shuriken', 'heroic', 'eldar'],
}

const obliteratorsPride: Item = {
  id: 'obliterators-pride',
  name: "Obliterator's Pride",
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d4',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Light', 'Silent'],
  ammoType: 'shot',
  ammoCapacity: 6,
  ammoName: 'Needle Dart',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Perfect Kill',
      description: 'Once per day, Obliterator\'s Pride can be loaded with a single Perfect Kill dart. This attack automatically hits and is automatically a critical hit. The target must succeed on a CON save DC 20 or instantly die. On a success, they take maximum weapon damage + 6d6 instead. Perfect Kills do not alert other creatures — the kill appears entirely natural.',
    },
  ],
  lore: 'The original Eversor Temple needle pistol from which all subsequent models were derived. Carried by the first Eversor who returned from a mission alive. He was debriefed, resanctified, and sent back. He never returned again, but the pistol did.',
  description: 'Base: Needle Pistol. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Perfect Kill (1/day): auto-hit, auto-crit; CON DC 20 or instant death; success = max damage + 6d6. Does not alert others.',
  cost: 'Unique',
  weight: 1,
  tags: ['ranged', 'named', 'needle', 'heroic', 'eversor'],
}

const thunderStrike: Item = {
  id: 'thunder-strike',
  name: 'Thunder Strike',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'heavy',
  rangeType: 'ranged',
  range: { normal: 60, long: 120 },
  damage: '2d6',
  damageType: 'fire',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Spread'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Promethium Tank',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Inferno of Salvation',
      description: 'Once per day, unleash a river of holy fire across a 60 ft line (10 ft wide). All creatures in the area take 6d6 fire damage (DEX save DC 18 for half) and are set On Fire (1d8 fire per turn). Chaos-marked and daemon targets automatically fail the save and take double damage. The flame burns for 1 minute and cannot be extinguished by mundane means.',
    },
  ],
  lore: 'The personal weapon of Saint Arabella, who held the breach at Gate 17 alone for four hours, immolating wave after wave of Chaos warriors until reinforcements arrived. The weapon was recovered from her hand after her martyrdom and classified a holy relic of the Adepta Sororitas.',
  description: 'Base: Flamer/Heavy Flamer. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Inferno of Salvation (1/day): 60 ft line 6d6 fire (DEX DC 18 half) + On Fire; chaos/daemons auto-fail and take double.',
  cost: 'Unique',
  weight: 10,
  tags: ['ranged', 'named', 'flamer', 'heroic', 'sororitas'],
}

const voidcaller: Item = {
  id: 'voidcaller',
  name: 'Voidcaller',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '2d10',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Silent'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'LEGENDARY: Called Shot',
      description: 'Once per combat, declare the exact location being targeted (head, leg, hand, eye, etc.). The attack auto-hits that location dealing 4d10 + 2d6 damage. Additional effect based on location: Head = CON DC 18 or instant death; Leg = movement 0 permanently until healed; Hand = disarmed, cannot use that hand; Eye = permanently blind in that eye (disadvantage on ranged attacks).',
    },
  ],
  lore: 'The only weapon in the Imperium documented to have killed three different Hive Tyrants with three consecutive shots in the same battle. Its wielder, Sergeant Vylar of the Deathwatch, called his shots aloud before each pull of the trigger. He had three bullets left when the battle ended. He was not asked what he planned to do with them.',
  description: 'Base: Sniper Rifle. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Called Shot (1/combat): 4d10+2d6 with location-specific effects (instant death, immobilise, disarm, or blind).',
  cost: 'Unique',
  weight: 7,
  tags: ['ranged', 'named', 'sniper', 'heroic', 'deathwatch'],
}

const theTorch: Item = {
  id: 'the-torch',
  name: 'The Torch',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  itemAbilities: [
    {
      name: 'LEGENDARY: Beacon of the Emperor',
      description: 'Once per day, The Torch fires a beam of pure golden light. All allies within 60 ft are fully healed to maximum HP and cured of all conditions. All enemies within 60 ft must make a WIS save DC 20 or be blinded and frightened for 1 minute. Daemons automatically fail and take 6d6 radiant damage.',
    },
  ],
  lore: 'The personal laspistol of Lord Solar Macharius, believed lost at his death. It was found in the hands of a child soldier who survived the Fall of Cadia. No one knows how it got there. The child does not remember. The weapon burns with golden light that intensifies in the presence of enemies.',
  description: 'Base: Laspistol. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Beacon of the Emperor (1/day): heal all allies to max HP + cure conditions; blind + frighten enemies WIS DC 20; daemons auto-fail + 6d6 radiant.',
  cost: 'Unique',
  weight: 2,
  tags: ['ranged', 'named', 'las', 'heroic', 'macharius'],
}

// ─── Melee ────────────────────────────────────────────────────────────────────

const emperorsFist: Item = {
  id: 'emperors-fist',
  name: "Emperor's Fist",
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d8',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Knockdown'],
  itemAbilities: [
    {
      name: 'LEGENDARY: The Emperor Judges',
      description: 'Once per day, Emperor\'s Fist can be slammed into the earth. A shockwave of divine energy expands 30 ft from the point of impact. All enemies in range take 6d8 bludgeoning + 6d8 radiant damage (CON save DC 20 for half) and are knocked prone. Daemons and Chaos entities auto-fail and are stunned for 1 round.',
    },
  ],
  lore: 'The thunder hammer used by a Custodian who defended the Golden Throne alone for six hours when the rest of the Custodians were diverted. He held every attack. The Throne\'s golden light permanently suffused the weapon, which now emanates warmth in the presence of loyal servants of the Emperor.',
  description: 'Base: Thunder Hammer. +3 to attack rolls. +2d6 bonus damage. LEGENDARY The Emperor Judges (1/day): 30 ft shockwave 6d8+6d8 radiant (CON DC 20 half), prone; daemons auto-fail and stunned.',
  cost: 'Unique',
  weight: 18,
  tags: ['melee', 'named', 'hammer', 'heroic', 'custodians'],
}

const deathsEmbrace: Item = {
  id: 'deaths-embrace',
  name: "Death's Embrace",
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Two-handed'],
  itemAbilities: [
    {
      name: "LEGENDARY: Dance of the Final Hour",
      description: 'Once per day, for 1 minute, Death\'s Embrace enters a state of perfect motion. During this time, you make 4 attacks instead of your normal amount on the Attack action, you cannot be reduced below 1 HP (automatically stabilised instead), and critical hits against you instead become normal hits.',
    },
  ],
  lore: 'A Callidus Temple blade that has killed fourteen planetary governors, three archbishops, two high lords, and an Eldar Phoenix Lord (who survived but remembers). The weapon was "retired" to deep storage. It disappeared from storage the following week. It reappears in the hands of those who have pledged their death to the Emperor\'s service.',
  description: 'Base: Power Sword. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Dance of the Final Hour (1/day): 1 minute — 4 attacks per action, cannot die (min 1 HP), crits against you become normal hits.',
  cost: 'Unique',
  weight: 3,
  tags: ['melee', 'named', 'sword', 'heroic', 'callidus'],
}

const starbreaker: Item = {
  id: 'starbreaker',
  name: 'Starbreaker',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d10',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed', 'Knockdown', 'Reach'],
  itemAbilities: [
    {
      name: 'LEGENDARY: World-Breaker',
      description: 'Once per day, bring Starbreaker down with full force. If used against a vehicle, fortification, or construct, it deals 20d10 bludgeoning damage. If used against a creature, it deals 10d10 + 2d6 and the creature must make a STR save DC 20 or be knocked back 30 ft and stunned for 2 rounds. The impact creates difficult terrain in a 20 ft radius.',
    },
  ],
  lore: 'A weapon that existed before the Imperium. It was carried by an Anathame-bearer during the Crusade, later recovered and blessed. The Mechanicus believe it is either a Terran weapon from the Age of Strife or xenos-derived. Both possibilities terrify them equally.',
  description: 'Base: Great Maul/Power Maul. +3 to attack rolls. +2d6 bonus damage. LEGENDARY World-Breaker (1/day): vs vehicles 20d10; vs creatures 10d10+2d6, STR DC 20 or 30 ft knockback + stunned 2 rounds + difficult terrain.',
  cost: 'Unique',
  weight: 22,
  tags: ['melee', 'named', 'hammer', 'heroic', 'crusade-era'],
}

const theClaw: Item = {
  id: 'the-claw',
  name: 'The Claw',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d10',
  damageType: 'slashing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  attackAbility: 'finesse',
  properties: ['Finesse', 'Rending'],
  itemAbilities: [
    {
      name: 'LEGENDARY: Rend the Unbreakable',
      description: 'Once per day, attack with The Claw at full supernatural force. Immediately deal 4d10 + 2d6 damage that ignores all damage resistances and immunities, including those provided by the warp, supernatural protection, or daemonic nature. The target is also inflicted with a permanent wound that reduces their maximum HP by 5.',
    },
  ],
  lore: 'A lightning claw taken from a World Eaters Berzerker mid-combat and reforged in Deathwatch facilities. The original machine spirit was excised; the replacement was sourced from the Black Library of Fenris. The weapon hungers. The wielder must be stronger than the hunger.',
  description: 'Base: Lightning Claw. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Rend the Unbreakable (1/day): 4d10+2d6 ignoring ALL resistances and immunities; permanent wound -5 max HP.',
  cost: 'Unique',
  weight: 4,
  tags: ['melee', 'named', 'claw', 'heroic', 'deathwatch'],
}

const annihilatorChain: Item = {
  id: 'annihilator-chain',
  name: 'Annihilator',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d8',
  damageType: 'slashing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed'],
  itemAbilities: [
    {
      name: 'LEGENDARY: Annihilation Arc',
      description: 'Once per day, swing Annihilator in a devastating arc. Make a separate attack roll against every creature within 15 ft. Each creature hit takes 3d8 + 2d6 slashing damage. Critical hits cause dismemberment — the target permanently loses a limb of your choice (GM discretion on mechanical effect). The roar of the chainswords deafens all creatures within 30 ft for 1 minute.',
    },
  ],
  lore: 'A Chainaxe of catastrophic proportions, built for a Space Wolves Wolf Lord who used it to personally dismember three Greater Daemons in a single campaign. The Black Wolves call it "The Silencer" because of what happens to the battlefield after it speaks.',
  description: 'Base: Great Chain Axe. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Annihilation Arc (1/day): attack all within 15 ft for 3d8+2d6; crits cause dismemberment; deafens 30 ft for 1 minute.',
  cost: 'Unique',
  weight: 16,
  tags: ['melee', 'named', 'chainsword', 'heroic', 'space-wolves'],
}

const faithUnbroken: Item = {
  id: 'faith-unbroken',
  name: 'Faith Unbroken',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  versatileDamage: '1d10',
  properties: ['Versatile (1d10)'],
  itemAbilities: [
    {
      name: 'LEGENDARY: Indestructible Faith',
      description: 'Once per day, strike with absolute faith. The attack deals 5d8 + 2d6 bludgeoning + 5d8 radiant damage. All allies within 60 ft who witness this strike are inspired: they gain 3d6 temporary HP, advantage on all saving throws for 1 minute, and cannot be reduced below 1 HP until their next long rest.',
    },
  ],
  lore: 'A crozius arcanum that survived the Siege of Terra in the hands of a Chaplain who preached throughout the entire assault, keeping thirty Astartes fighting beyond mortal limits through sheer force of faith. After the siege ended he placed it at the foot of the Golden Throne and never picked it up again. It returned to him by morning.',
  description: 'Base: Crozius Arcanum/Mace. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Indestructible Faith (1/day): 5d8+5d8 radiant; all allies 60 ft gain 3d6 temp HP, advantage on saves 1 min, cannot fall below 1 HP until long rest.',
  cost: 'Unique',
  weight: 5,
  tags: ['melee', 'named', 'mace', 'heroic', 'chaplain'],
}

const theWordAndTheSword: Item = {
  id: 'the-word-and-the-sword',
  name: 'The Word and the Sword',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d6',
  damageType: 'psychic',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  attackAbility: 'finesse',
  properties: ['Finesse', 'Reach'],
  itemAbilities: [
    {
      name: 'LEGENDARY: The Emperor\'s Voice',
      description: 'Once per day, speak the Emperor\'s true name while striking. The target is struck by the full weight of the divine: they take 6d6 psychic + 6d6 radiant damage and must make a WIS save DC 22 or be utterly destroyed — their soul consumed and unable to be resurrected by any power in the galaxy. On a successful save, they are reduced to 1 HP and permanently frightened of the wielder.',
    },
  ],
  lore: 'A force sword that was present when the Emperor sealed the webway gate beneath the Palace. The sword absorbed something of His will that day. Psykers in its presence feel the weight of ten thousand years of divine sacrifice pressing against their mind. Non-psykers feel only warmth.',
  description: 'Base: Force Sword. +3 to attack rolls. +2d6 bonus damage. LEGENDARY The Emperor\'s Voice (1/day): 6d6 psychic + 6d6 radiant; WIS DC 22 or soul destroyed (no resurrection); success = 1 HP + permanent fear of wielder.',
  cost: 'Unique',
  weight: 3,
  tags: ['melee', 'named', 'sword', 'heroic', 'psychic', 'webway'],
}

const chainbreakerAxe: Item = {
  id: 'chainbreaker',
  name: 'Chainbreaker',
  type: 'weapon',
  tier: 'heroic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d12',
  damageType: 'slashing',
  bonusAttack: 3,
  bonusDamageDice: '+2d6',
  properties: ['Heavy', 'Two-handed'],
  itemAbilities: [
    {
      name: 'LEGENDARY: Break Every Chain',
      description: 'Once per day, when you attack a creature that is enslaved, dominated, possessed, bound, charmed, or mind-controlled, the attack automatically hits and is automatically a critical hit, dealing maximum damage. All magical compulsions and bindings on the target are immediately ended by the impact. The shock of freedom grants them 6d10 temporary HP and advantage on all rolls for 1 minute.',
    },
  ],
  lore: 'An axe carried by a freed slave who rose to command the liberation of an entire system from Dark Eldar slavers. She carried it through twelve campaigns, a hundred worlds, and one Inquisitorial tribunal that declared her a heretic for the company she kept. She walked out of the tribunal. The Inquisitor did not.',
  description: 'Base: Great Axe. +3 to attack rolls. +2d6 bonus damage. LEGENDARY Break Every Chain (1/day): auto-crit vs enslaved/dominated/compelled creatures; removes all magical bindings; target gains 6d10 temp HP + advantage 1 min.',
  cost: 'Unique',
  weight: 12,
  tags: ['melee', 'named', 'axe', 'heroic', 'liberator'],
}

export const namedWeaponsHeroic: Item[] = [
  godkiller,
  starFire,
  ironVoice,
  omnissiahsGaze,
  astartesForgiven,
  starlightShuriken,
  obliteratorsPride,
  thunderStrike,
  voidcaller,
  theTorch,
  emperorsFist,
  deathsEmbrace,
  starbreaker,
  theClaw,
  annihilatorChain,
  faithUnbroken,
  theWordAndTheSword,
  chainbreakerAxe,
]
