import type { Item } from '../../../types/module'

// ─── Named Weapons: Master-Crafted ───────────────────────────────────────────
// +1 to attack, +1 flat damage (bonusDamage: 1). No unique traits.
// isNamed: true on every item.

// ── Ranged ────────────────────────────────────────────────────────────────────

const vostroyaFirstBornLasgun: Item = {
  id: 'vostroyan-first-born-lasgun',
  name: 'Vostroyan First-Born Lasgun',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 80, long: 320 },
  damage: '1d8',
  damageType: 'energy',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Rapid Fire'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  lore: 'Among the Vostroyans, the firstborn of every family is given to the Imperial Guard as tithe. With them goes a weapon, hand-crafted by the family\'s weaponsmith and engraved with the dynasty\'s history. These lasguns are maintained across generations, each successive owner adding their own mark to the stock. They are not merely weapons — they are heirlooms.',
  description: 'Base: Lasgun. +1 to attack rolls. Ornately engraved — advantage on Persuasion with Vostroyan military contacts.',
  cost: 'Rare',
  weight: 5,
  tags: ['ranged', 'named', 'las', 'vostroyan'],
}

const gunmetalCitySpecial: Item = {
  id: 'gunmetal-city-special',
  name: 'Gunmetal City Special',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d8',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: [],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Cylinder (6)',
  rechargeable: false,
  lore: 'Gunmetal City on Scintilla is famous for two things: crime and firearms. The \'Special\' is a hand-tooled stub revolver favored by Magistratum investigators and bounty hunters. Its cylinder has been bored to accept oversized rounds, and the barrel has been lengthened and rifled by hand.',
  description: 'Base: Stub Revolver. +1 to attack rolls. Conceals easily — Perception checks to spot this weapon are at disadvantage.',
  cost: 'Rare',
  weight: 3,
  tags: ['ranged', 'named', 'stub'],
}

const scintillanDuelingPistol: Item = {
  id: 'scintillan-dueling-pistol',
  name: 'Scintillan Dueling Pistol',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'energy',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  lore: 'The noble houses of Scintilla settle their disputes with dueling pistols — ornate, single-shot laspistols crafted with the precision of surgical instruments. The focusing crystal is cut to produce a beam so tight it can burn through a coin at fifty paces.',
  description: 'Base: Laspistol. +1 to attack rolls. When making only a single ranged attack on your turn (not Rapid Fire), gain an additional +2 to the attack roll.',
  cost: 'Rare',
  weight: 2,
  tags: ['ranged', 'named', 'las', 'scintilla'],
}

const kriegLuciusNo98: Item = {
  id: 'krieg-lucius-no-98',
  name: 'Krieg Pattern Lucius No. 98',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 100, long: 400 },
  damage: '1d8',
  damageType: 'energy',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Rapid Fire'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  lore: 'The Death Korps of Krieg produce their own variant of the standard lasgun in the underground manufactories beneath their irradiated homeworld. No ornamentation. No comfort features. The stock is bare metal because Krieg Guardsmen do not complain about cold hands.',
  description: 'Base: Lasgun. +1 to attack rolls. Extended barrel grants +20 ft to both range increments.',
  cost: 'Rare',
  weight: 5,
  tags: ['ranged', 'named', 'las', 'krieg'],
}

const hiveRunnersPiece: Item = {
  id: 'hive-runners-piece',
  name: 'Hive Runner\'s Piece',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 30, long: 120 },
  damage: '1d6',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Light', 'Rapid Fire'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Magazine',
  rechargeable: false,
  lore: 'In the underhives, a Hive Runner is a courier — someone who carries messages, packages, and contraband between gang territories. Survival depends on speed, stealth, and a weapon you can draw faster than the other guy.',
  description: 'Base: Autopistol. +1 to attack rolls. Quick draw: advantage on initiative while carrying. Drawing costs no action.',
  cost: 'Rare',
  weight: 2,
  tags: ['ranged', 'named', 'auto', 'underhive'],
}

const armageddonShotcannon: Item = {
  id: 'armageddon-shotcannon',
  name: 'Armageddon-Pattern Shotcannon',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 90 },
  damage: '1d10',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Spread', 'Rapid Fire'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Shell Box (8)',
  rechargeable: false,
  lore: 'Armageddon\'s hive cities breed a particular kind of close-quarters combat. The Shotcannon was designed for exactly this kind of work — short barrel, tight choke, hand-tuned action.',
  description: 'Base: Combat Shotgun. +1 to attack rolls. In enclosed spaces (corridors, rooms, tunnels), Spread bonus increases to +2 instead of +1.',
  cost: 'Rare',
  weight: 7,
  tags: ['ranged', 'named', 'shotgun', 'armageddon'],
}

const tanithNalwoodLongLas: Item = {
  id: 'tanith-nalwood-long-las',
  name: 'Tanith Nalwood Long-Las',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d10',
  damageType: 'energy',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Power Pack',
  rechargeable: true,
  lore: 'Before Tanith was destroyed, its woodsmen were famous for two things: stealth and marksmanship. The Tanith Long-Las has a stock carved from nalwood, a tree native to Tanith whose grain shifts and changes color to match its surroundings.',
  description: 'Base: Long-Las. +1 to attack rolls. Advantage on Stealth while prone and wielding. Emits no visible beam in darkness.',
  cost: 'Rare',
  weight: 8,
  tags: ['ranged', 'named', 'las', 'tanith'],
}

const graiaPatternBolter: Item = {
  id: 'graia-pattern-bolter',
  name: 'Graia Pattern Bolter',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 80, long: 320 },
  damage: '1d12',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Rapid Fire', 'Rending'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Bolt Magazine',
  rechargeable: false,
  lore: 'Forge World Graia produces a bolter variant with a marginally tighter bore and hand-inspected bolt shells. The tech-priests do not care about logistics officers\' frustrations. They are correct, and correctness matters more than convenience.',
  description: 'Base: Boltgun. +1 to attack rolls. Crits on 19–20. Only fires Graia-pattern bolt shells (Uncommon availability outside Graia supply lines).',
  cost: 'Rare',
  weight: 7,
  tags: ['ranged', 'named', 'bolt', 'graia'],
}

const mordianIronGuardPistol: Item = {
  id: 'mordian-iron-guard-pistol',
  name: 'Mordian Iron Guard Pistol',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'energy',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  lore: 'The Mordian Iron Guard are famous for their discipline — uniforms pressed, boots polished, weapons immaculate even under fire. Their officer\'s sidearm reflects this: a laspistol with mirror-polished casing and a distinctive blue beam.',
  description: 'Base: Laspistol. +1 to attack rolls. Advantage on Persuasion with military/law enforcement personnel.',
  cost: 'Rare',
  weight: 2,
  tags: ['ranged', 'named', 'las', 'mordian'],
}

const ratlingChefsSpecial: Item = {
  id: 'ratling-chefs-special',
  name: 'Ratling Chef\'s Special',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d10',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Magazine',
  rechargeable: false,
  lore: 'The Chef\'s Special is a sniper rifle that doubles as a cooking spit. Literally. The barrel unscrews from the stock to serve as a roasting rod, and the bipod doubles as a pot stand. Ratling \'Peppers\' claimed he could kill a target at eight hundred meters and have dinner ready by the time the squad reached the body.',
  description: 'Base: Sniper Rifle. +1 to attack rolls. Doubles as cook\'s utensils. While prone, add proficiency bonus twice to attack rolls.',
  cost: 'Rare',
  weight: 6,
  tags: ['ranged', 'named', 'sniper', 'ratling'],
}

// ── Melee ─────────────────────────────────────────────────────────────────────

const catachanFang: Item = {
  id: 'catachan-fang',
  name: 'Catachan Fang',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d4',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Thrown (20/60)'],
  lore: 'The Catachan Fang is not a single weapon but a tradition. Every Catachan Devil who survives their first year in the jungle earns the right to forge their own blade from the tooth of a Catachan Devil. The tooth-steel holds an edge like nothing else in the Imperium.',
  description: 'Base: Combat Knife. +1 to attack rolls. Immune to corrosion. Advantage on Survival checks in wilderness.',
  cost: 'Rare',
  weight: 1,
  tags: ['melee', 'named', 'knife', 'catachan'],
}

const forgeBlessedChainsword: Item = {
  id: 'forge-blessed-chainsword',
  name: 'Forge-Blessed Chainsword',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Rending'],
  lore: 'Before a chainsword leaves the forges of a major Forge World, the most promising blades are set aside for individual blessing by a tech-priest of the Cult Mechanicus. The teeth are anointed with sacred oils, the motor housing is inscribed with micro-litanies. A Forge-Blessed chainsword doesn\'t just cut — it wants to cut.',
  description: 'Base: Chainsword. +1 to attack rolls. Crits on 19–20. Never jams. Never requires field maintenance.',
  cost: 'Rare',
  weight: 4,
  tags: ['melee', 'named', 'chain'],
}

const cadianOfficerSabre: Item = {
  id: 'cadian-officers-sabre',
  name: 'Cadian Officer\'s Sabre',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  versatileDamage: '1d10',
  properties: ['Versatile (1d10)'],
  lore: 'Cadian officers carry sabres not as their primary weapon — that would be impractical in a warzone — but as a symbol of rank and a reminder that an officer must be willing to lead from the front. Inscribed with "The Gate Holds."',
  description: 'Base: Sword. +1 to attack rolls. Versatile (1d10). Allies within 10 ft gain +1 to morale saves.',
  cost: 'Rare',
  weight: 3,
  tags: ['melee', 'named', 'sword', 'cadian'],
}

const magistratumShockBaton: Item = {
  id: 'magistratum-shock-baton',
  name: 'Magistratum Shock Baton',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'bludgeoning',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Stun (CON save DC 13)'],
  lore: 'Hand-modified: boosted capacitor, conductive grip, lead-weighted striking surface. Technically against regulations. Also technically against regulations to be an enforcer who can\'t handle an underbelly brawl.',
  description: 'Base: Shock Maul. +1 to attack rolls. Deals 1d6 bludgeoning + 1d4 lightning. Stun (CON DC 13). Non-lethal: can knock unconscious instead of killing.',
  cost: 'Rare',
  weight: 3,
  tags: ['melee', 'named', 'baton', 'arbites'],
}

const pitFightersAxe: Item = {
  id: 'pit-fighters-axe',
  name: 'Pit Fighter\'s Axe',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  versatileDamage: '1d10',
  properties: ['Versatile (1d10)'],
  lore: 'In the fighting pits of Necromunda, a weapon is an extension of your brand. This axe was built for a pit fighter known as "The Headsman" — it has an oversized crescent blade, a weighted pommel, and a haft wrapped in red synth-leather. The Headsman won forty-seven consecutive bouts before earning his freedom.',
  description: 'Base: War Axe. +1 to attack rolls. Versatile (1d10). Advantage on Intimidation checks while wielding visibly.',
  cost: 'Rare',
  weight: 5,
  tags: ['melee', 'named', 'axe', 'necromunda'],
}

const tallarnSandviper: Item = {
  id: 'tallarn-sandviper',
  name: 'Tallarn Sandviper',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Armor Penetration'],
  lore: 'A curved mono-knife designed for close-quarters throat-cutting during desert patrol encounters. The blade\'s curve follows the natural wrist-slash, coated in sand-repellent resin.',
  description: 'Base: Mono-Knife. +1 to attack rolls. Finesse. Armor Penetration (ignores 2 AC). Attacks from hiding or surprise deal +1d4 damage.',
  cost: 'Rare',
  weight: 1,
  tags: ['melee', 'named', 'knife', 'tallarn'],
}

const miningsSalvation: Item = {
  id: 'miners-salvation',
  name: 'Miner\'s Salvation',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  properties: ['Light'],
  lore: 'Rebalanced for combat during a Sepheris Secundus miners\' rebellion. Spike sharpened, haft wrapped in overseer\'s leather. Carried by rebel leader Grent, who killed eleven overseers. He was executed. The pick survived.',
  description: 'Base: Mining Pick. +1 to attack rolls. Advantage on checks to break objects/barriers. Double damage to inanimate objects.',
  cost: 'Rare',
  weight: 4,
  tags: ['melee', 'named', 'pick'],
}

const penalLegionnaireShiv: Item = {
  id: 'penal-legionnaire-shiv',
  name: 'Penal Legionnaire\'s Shiv',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d4',
  damageType: 'piercing',
  bonusAttack: 1,
  bonusDamage: 1,
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Thrown (20/60)'],
  lore: 'When you\'re sentenced to a Penal Legion, they take your name, your rank, and your equipment. This particular shiv was made by Prisoner 4471, who spent three weeks filing a spoon handle into a blade. He survived his sentence — one of four from a battalion of eight hundred.',
  description: 'Base: Combat Knife. +1 to attack rolls. Concealable (impossible to detect without thorough search). Unaware targets take +1d6 damage.',
  cost: 'Rare',
  weight: 1,
  tags: ['melee', 'named', 'knife', 'penal'],
}

const kriegEntrechingTool: Item = {
  id: 'krieg-entrenching-tool',
  name: 'Krieg Entrenching Tool',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'slashing',
  bonusAttack: 1,
  bonusDamage: 1,
  versatileDamage: '1d8',
  properties: ['Versatile (1d8)'],
  lore: 'The Death Korps of Krieg are famous for trench warfare, and their standard-issue entrenching tool reflects this obsession. Hand-forged from Krieg steel, it digs foxholes, cuts barbed wire, and splits skulls. Krieg Guardsmen consider it their third most important piece of equipment.',
  description: 'Base: Shovel. +1 to attack rolls. Versatile (1d8). Dig a foxhole providing half cover in 10 minutes. When fighting from a trench or foxhole you dug, gain +1 AC.',
  cost: 'Rare',
  weight: 4,
  tags: ['melee', 'named', 'shovel', 'krieg'],
}

const ecclesiarchyCenserMace: Item = {
  id: 'ecclesiarchy-censer-mace',
  name: 'Ecclesiarchy Censer-Mace',
  type: 'weapon',
  tier: 'master-crafted',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'bludgeoning',
  bonusAttack: 1,
  bonusDamage: 1,
  versatileDamage: '1d8',
  properties: ['Versatile (1d8)'],
  lore: 'The Ecclesiarchy arms its battle-priests with weapons that double as holy implements. This censer-mace was wielded by Confessor Kael during the Macharian Crusade. The incense blend he used — "the Emperor\'s Perfume" — is so potent it causes nausea in the unrighteous.',
  description: 'Base: Mace. +1 to attack rolls. Versatile (1d8). Advantage on Intimidation vs chaos enemies. Allies within 10 ft have advantage on saves vs fear.',
  cost: 'Rare',
  weight: 4,
  tags: ['melee', 'named', 'mace', 'ecclesiarchy'],
}

export const namedWeaponsMasterCrafted: Item[] = [
  vostroyaFirstBornLasgun,
  gunmetalCitySpecial,
  scintillanDuelingPistol,
  kriegLuciusNo98,
  hiveRunnersPiece,
  armageddonShotcannon,
  tanithNalwoodLongLas,
  graiaPatternBolter,
  mordianIronGuardPistol,
  ratlingChefsSpecial,
  catachanFang,
  forgeBlessedChainsword,
  cadianOfficerSabre,
  magistratumShockBaton,
  pitFightersAxe,
  tallarnSandviper,
  miningsSalvation,
  penalLegionnaireShiv,
  kriegEntrechingTool,
  ecclesiarchyCenserMace,
]
