import type { Item } from '../../../types/module'

// ─── Ranged ───────────────────────────────────────────────────────────────────

const handOfOmnissiah: Item = {
  id: 'hand-of-omnissiah',
  name: 'Hand of the Omnissiah',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  itemAbilities: [
    {
      name: 'Machine Communion',
      description: 'As an action, you may interface with any mechanical device within 10 ft, instantly understanding its function, current state, and any faults. Once per rest you can also force a mechanical device to malfunction for 1 minute (no save for non-sentient machines).',
    },
  ],
  lore: 'A laspistol that pre-dates the Horus Heresy, carried by a Mechanicus Magos who participated in the Council of Nikaea. Its machine spirit is ancient and deeply learned, having survived ten thousand years of warfare.',
  description: 'Base: Laspistol. +3 to attack rolls. +2d4 bonus damage. Machine Communion: instantly analyse/understand any device within 10 ft; 1/rest force non-sentient device to malfunction.',
  cost: 'Legendary',
  weight: 2,
  tags: ['ranged', 'named', 'las', 'mechanicus', 'heresy-era'],
}

const thronesWill: Item = {
  id: 'thrones-will',
  name: "The Throne's Will",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 80, long: 240 },
  damage: '1d8',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Rapid Fire (1)'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Bolt Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Divine Retribution',
      description: 'Attacks against psykers, daemons, and Chaos-marked entities deal an additional 2d6 radiant damage. Additionally, when wielded by a person of pure faith (GM discretion), the weapon ignores damage resistances against such targets.',
    },
  ],
  lore: 'A boltgun blessed by Macharius himself before the great Crusade and touched by three Ecclesiarchs since. The ammunition is hand-blessed holy bolts. The weapon is theoretically the property of the Adeptus Ministorum but tends to find its way to those the Emperor deems worthy.',
  description: 'Base: Boltgun. +3 to attack rolls. +2d4 bonus damage. Divine Retribution: +2d6 radiant vs psykers/daemons/chaos; ignores resistances when wielded by true believer.',
  cost: 'Legendary',
  weight: 7,
  tags: ['ranged', 'named', 'bolt', 'macharius', 'ecclesiarchy'],
}

const dragonsFang: Item = {
  id: 'dragons-fang',
  name: "Dragon's Fang",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 60 },
  damage: '2d6',
  damageType: 'fire',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed', 'Spread', 'Melta'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Promethium Tank',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Dragon\'s Breath',
      description: 'Once per rest, Dragon\'s Fang can be fired in a devastating Melta-Flamer burst. All creatures in a 20 ft cone take 4d8 fire damage + 2d8 melta damage (CON save DC 16 for half). Armoured targets (AC 15+) take the full melta damage with no save.',
    },
  ],
  lore: 'A Salamanders Chapter relic — a master-crafted flamer-melta combination weapon built by the legendary artificer Brother Salamandar Hestan. Carried for three centuries before being gifted to a mortal champion who saved a Salamanders battle-brother from certain death.',
  description: 'Base: Flamer/Meltagun hybrid. +3 to attack rolls. +2d4 bonus damage. Dragon\'s Breath (1/rest): 20 ft cone, 4d8 fire + 2d8 melta, CON DC 16 half (armoured take full melta).',
  cost: 'Legendary',
  weight: 12,
  tags: ['ranged', 'named', 'flamer', 'melta', 'salamanders'],
}

const forgeBreakerCannon: Item = {
  id: 'forge-breaker-cannon',
  name: 'Forge-Breaker Cannon',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'heavy',
  rangeType: 'ranged',
  range: { normal: 60, long: 180 },
  damage: '4d8',
  damageType: 'heat',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed', 'Mounted', 'Melta'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Promethium Canister',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Armour Ablation',
      description: 'On a hit, the target\'s armour (or natural armour) is partially ablated. Reduce their AC by 1 (to a minimum of 10) for 24 hours or until repaired. This effect stacks up to 3 times. Vehicles and fortifications can also be ablated.',
    },
  ],
  lore: 'Used to breach the walls of the Fortress-Manufactorum of Vraks, this multi-melta was modified to focus its beam to a sustained cutting discharge rather than a single pulse. The Adeptus Mechanicus recovered it from the rubble and classified it as a Relic of the Machine God.',
  description: 'Base: Multi-Melta. +3 to attack rolls. +2d4 bonus damage. Armour Ablation: hits reduce target AC by 1 (stacks 3×, min AC 10) for 24 hours.',
  cost: 'Legendary',
  weight: 25,
  tags: ['ranged', 'named', 'melta', 'vraks'],
}

const stormcallerBow: Item = {
  id: 'stormcaller-bow',
  name: 'Stormcaller',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d8',
  damageType: 'lightning',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'shot',
  ammoCapacity: 20,
  ammoName: 'Arrow',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Chain Lightning Arrow',
      description: 'Once per rest, you may fire an arrow that, on a hit, arcs to up to 3 additional targets within 30 ft of the primary target. Each additional target takes 2d6 lightning damage (DEX save DC 15 for half).',
    },
  ],
  lore: 'A Fenrisian sacred bow, crafted by the Skjalds for a Rune Priest who fought alongside Space Wolves during a Fenrisian winter. Each arrow is fletched with eagle feathers and the bowstring is woven from storm-giant hair. It is the oldest weapon of purely human origin still in active use.',
  description: 'Base: Longbow. Damage type: lightning. +3 to attack rolls. +2d4 bonus damage. Chain Lightning Arrow (1/rest): arcs to 3 additional targets within 30 ft for 2d6 lightning each.',
  cost: 'Legendary',
  weight: 3,
  tags: ['ranged', 'named', 'bow', 'fenris', 'space-wolves'],
}

const umbralNeedle: Item = {
  id: 'umbral-needle',
  name: 'Umbral Needle',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d4',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Light', 'Silent'],
  ammoType: 'shot',
  ammoCapacity: 6,
  ammoName: 'Needle Dart',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Soporific Compound',
      description: 'On a hit, the target must succeed on a CON save (DC 16) or fall unconscious for 1 hour. The save DC increases to 18 on a critical hit. Creatures immune to poison are unaffected. Coup de grace immediately fails this save.',
    },
  ],
  lore: 'A Callidus Temple assassination tool of exceptional age, constructed from a xenos alloy that reflects no light whatsoever. The compound it delivers was developed over centuries. One dart has never failed to drop its target in recorded Temple history.',
  description: 'Base: Needle Pistol. +3 to attack rolls. +2d4 bonus damage. Soporific Compound: CON DC 16 (DC 18 on crit) or unconscious 1 hour. Coup de grace auto-fails.',
  cost: 'Legendary',
  weight: 1,
  tags: ['ranged', 'named', 'needle', 'callidus', 'assassin'],
}

const thunderhandCarbine: Item = {
  id: 'thunderhand-carbine',
  name: 'Thunderhand',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 80, long: 240 },
  damage: '1d8',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Rapid Fire (1)'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Bolt Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Thunder and Lightning',
      description: 'Once per rest, you may fire all remaining rounds in a single devastating burst (uses remaining ammo count as attack rolls at +3, each successful hit deals weapon damage + 2d4). Minimum 2 rounds remaining to activate.',
    },
  ],
  lore: 'A bolt carbine that survived the Battle of Terra and was carried by a Custodian Guard\'s personal attendant for three centuries. The weapon is said to have fired the shot that killed the last major Chaos commander during the Siege. The attendant died on the steps of the Palace.',
  description: 'Base: Bolt Carbine. +3 to attack rolls. +2d4 bonus damage. Thunder and Lightning (1/rest): expend all remaining ammo, each round becomes an attack at +3.',
  cost: 'Legendary',
  weight: 5,
  tags: ['ranged', 'named', 'bolt', 'battle-of-terra'],
}

const voidhawkPulse: Item = {
  id: 'voidhawk-pulse',
  name: 'Voidhawk',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 60, long: 180 },
  damage: '2d8',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Power Cell',
  rechargeable: true,
  itemAbilities: [
    {
      name: 'Overcharge Pulse',
      description: 'Once per rest, fire an overcharged burst dealing 4d8 + 2d4 energy damage. All other creatures (friend or foe) within 10 ft of the target take 2d8 energy damage from the pulse discharge (DEX save DC 15 for half).',
    },
  ],
  lore: 'A Tau ion rifle recovered from a Commander\'s battlesuit by an Inquisitor who valued efficiency over doctrine. Heavily modified for human use and blessed by a Techpriest who preferred not to ask too many questions about its origins.',
  description: 'Base: Ion Rifle/Pulse Rifle. +3 to attack rolls. +2d4 bonus damage. Overcharge Pulse (1/rest): 4d8+2d4 vs target, 2d8 splash to all within 10 ft (DEX DC 15 half).',
  cost: 'Legendary',
  weight: 9,
  tags: ['ranged', 'named', 'tau', 'xenos', 'pulse'],
}

const deathsWhisper: Item = {
  id: 'deaths-whisper',
  name: "Death's Whisper",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d10',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed', 'Silent'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'One in a Million',
      description: 'Once per encounter, before making an attack roll, you may declare this shot must hit. The attack automatically hits (no roll required). If the target\'s AC is 20 or higher, this instead provides advantage on the roll and adds +10 to the result.',
    },
  ],
  lore: 'A Vindicare Temple rifle of unrecorded manufacture. No Temple records acknowledge its existence. The single notch on the stock represents the only shot that has ever missed in its recorded history — and even then, the bullet struck the assassin standing next to the target.',
  description: 'Base: Sniper Rifle. +3 to attack rolls. +2d4 bonus damage. One in a Million (1/encounter): declare auto-hit; AC 20+ gives advantage and +10 instead.',
  cost: 'Legendary',
  weight: 7,
  tags: ['ranged', 'named', 'sniper', 'vindicare', 'assassin'],
}

const plasmaBrand: Item = {
  id: 'plasma-brand',
  name: 'Plasma Brand',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 90 },
  damage: '2d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Plasma Flask',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Plasma Vortex',
      description: 'On a critical hit, instead of normal extra damage, the plasma round detonates in a vortex. All creatures within 10 ft of the target take 3d6 energy damage (DEX save DC 16 half). The vortex remains for 1 round; any creature ending their turn in it takes 2d6 damage.',
    },
  ],
  lore: 'A plasma gun fitted with an unstable but beautiful plasma containment coil of pre-Heresy design. Normal plasma containment is a cage. This is a lens — focusing the plasma vortex instead of merely channelling it. The Mechanicus considers it heretical. It also considers it a masterwork.',
  description: 'Base: Plasma Gun. No Gets Hot. +3 to attack rolls. +2d4 bonus damage. Plasma Vortex: crits trigger 10 ft blast 3d6 energy (DEX DC 16 half); vortex lingers 1 round.',
  cost: 'Legendary',
  weight: 8,
  tags: ['ranged', 'named', 'plasma', 'mechanicus', 'heresy-era'],
}

// ─── Melee ────────────────────────────────────────────────────────────────────

const emperorsEdge: Item = {
  id: 'emperors-edge',
  name: "Emperor's Edge",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d6',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Two-handed'],
  itemAbilities: [
    {
      name: 'Anathema',
      description: 'Attacks against daemons, heretics bearing Chaos marks, and warp entities deal an additional 3d6 radiant damage and cannot be resisted or reduced by any means. Daemons struck by this weapon must make a WIS save (DC 17) or be banished to the Warp for 1 minute.',
    },
  ],
  lore: 'A power sword blessed by the High Lords of Terra and carried into battle personally by Saint Celestine during the Thirteenth Black Crusade. After the war, it passed to the Ecclesiarchy where it was deemed too holy to be held by one person — so it passed between champions of the faith.',
  description: 'Base: Power Sword. +3 to attack rolls. +2d4 bonus damage. Anathema: vs daemons/chaos +3d6 unresistable radiant, daemons WIS DC 17 or banished 1 minute.',
  cost: 'Legendary',
  weight: 5,
  tags: ['melee', 'named', 'sword', 'celestine', 'ecclesiarchy'],
}

const ironclawHammer: Item = {
  id: 'ironclaw-hammer',
  name: 'Ironclaw',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d8',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed', 'Knockdown'],
  itemAbilities: [
    {
      name: 'Seismic Smash',
      description: 'Once per rest, slam Ironclaw into the ground. All creatures within a 15 ft radius must succeed on a STR save (DC 16) or be knocked prone and stunned for 1 round. The ground in the radius becomes difficult terrain.',
    },
  ],
  lore: 'A thunder hammer carried by an Iron Hands Chapter Champion for two hundred years. The Iron Hands call it Ironclaw to mock the soft flesh that other Chapters retain. The Champion who carried it sacrificed both arms for bionic replacements just to wield it more effectively.',
  description: 'Base: Thunder Hammer. +3 to attack rolls. +2d4 bonus damage. Seismic Smash (1/rest): 15 ft radius STR DC 16 or prone + stunned 1 round, difficult terrain.',
  cost: 'Legendary',
  weight: 18,
  tags: ['melee', 'named', 'hammer', 'iron-hands'],
}

const obliteratorsThorn: Item = {
  id: 'obliterators-thorn',
  name: "Obliterator's Thorn",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'piercing',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Armor Penetration'],
  itemAbilities: [
    {
      name: 'Vitals Strike',
      description: 'Once per combat, declare a Vitals Strike before rolling. On a hit, the target takes triple damage and must succeed on a CON save (DC 16) or gain a level of Exhaustion. On a miss, this ability is not expended.',
    },
  ],
  lore: 'A relic of the Eversor Temple — a mono-blade so finely honed that it cuts between the fibres of power armour joints. Temple records show this specific blade has killed three Chaos Space Marines. Not three in its history. Three in one battle.',
  description: 'Base: Mono-Knife. +3 to attack rolls. +2d4 bonus damage. Vitals Strike (1/combat): on hit, triple damage + CON DC 16 or gain Exhaustion level.',
  cost: 'Legendary',
  weight: 1,
  tags: ['melee', 'named', 'knife', 'eversor', 'assassin'],
}

const sacredThrone: Item = {
  id: 'sacred-throne',
  name: 'Sacred Throne',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  versatileDamage: '1d10',
  properties: ['Versatile (1d10)', 'Stun (CON save DC 15)'],
  itemAbilities: [
    {
      name: 'Judgement of Terra',
      description: 'Attacks against traitors, heretics, and apostates are automatically critical hits. Against all other targets, on a hit you may spend your bonus action to force a WIS save (DC 16) or cause the target to kneel in involuntary reverence for 1 round (cannot attack or move).',
    },
  ],
  lore: 'A golden mace held by an Ecclesiarchal Legate who served as personal representative of the High Lords. It was carried from Terra to a hundred worlds. Every world it touched felt the weight of the Golden Throne\'s authority.',
  description: 'Base: Mace. +3 to attack rolls. +2d4 bonus damage. Judgement of Terra: auto-crit vs traitors/heretics; vs others, bonus action WIS DC 16 or kneels 1 round.',
  cost: 'Legendary',
  weight: 4,
  tags: ['melee', 'named', 'mace', 'ecclesiarchy', 'terra'],
}

const stellarForge: Item = {
  id: 'stellar-forge',
  name: 'Stellar Forge',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d10',
  damageType: 'energy',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Two-handed', 'Reach'],
  itemAbilities: [
    {
      name: 'Nova Strike',
      description: 'Once per rest, Stellar Forge\'s plasma coils discharge in a wide arc. Make an attack roll against every creature within 10 ft. Each creature hit takes 2d10 energy damage + 2d4 bonus damage. Critical hits against any target trigger a bonus 1d10 splash to all creatures within 5 ft of that target.',
    },
  ],
  lore: 'A plasma-edged halberd constructed in the forges of Morvenn Vahl\'s personal Argent Shroud. The plasma coils run along the polearm\'s full length, making it a weapon of exceptional reach and devastating arc attacks.',
  description: 'Base: Power Halberd/Polearm. +3 to attack rolls. +2d4 bonus damage. Nova Strike (1/rest): attack all creatures within 10 ft for 2d10 + 2d4 each.',
  cost: 'Legendary',
  weight: 8,
  tags: ['melee', 'named', 'halberd', 'adepta-sororitas'],
}

const worldsBurden: Item = {
  id: 'worlds-burden',
  name: "World's Burden",
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d12',
  damageType: 'bludgeoning',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  properties: ['Heavy', 'Two-handed', 'Knockdown'],
  itemAbilities: [
    {
      name: 'Load-Bearing',
      description: 'When you strike a fortification, vehicle, or construct, you deal double dice damage. Against creatures in heavy armour (AC 17+), your attacks ignore 5 points of AC. Once per rest, you may use this weapon to brace: until your next turn, you count as immovable and all allies within 10 ft have half cover from your bulk.',
    },
  ],
  lore: 'A Cadian monument to stubbornness — a siege hammer so large it was carried in a dedicated vehicle. The Cadians at Gate 17 carried it by hand for six miles across broken terrain to break through a wall that had held for three years. The gate didn\'t survive. Neither did most of the regiment.',
  description: 'Base: Great Hammer. +3 to attack rolls. +2d4 bonus damage. Load-Bearing: double damage vs fortifications/constructs; ignore 5 AC vs heavy armour; 1/rest: Brace for cover.',
  cost: 'Legendary',
  weight: 20,
  tags: ['melee', 'named', 'hammer', 'cadia', 'siege'],
}

const veilParting: Item = {
  id: 'veil-parting',
  name: 'Veil-Parting',
  type: 'weapon',
  tier: 'relic',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'psychic',
  bonusAttack: 3,
  bonusDamageDice: '+2d4',
  attackAbility: 'finesse',
  properties: ['Finesse', 'Reach'],
  itemAbilities: [
    {
      name: 'Through the Veil',
      description: 'Attacks with Veil-Parting can target incorporeal and warp-manifested creatures as if they were physical. Against psykers and daemons, critical hits force a PSY check (DC 16) or the target\'s psychic abilities are suppressed for 1 minute.',
    },
  ],
  lore: 'A witchblade of unknown xenos origin, confiscated from a rogue psyker and later reclassified as "sanctioned" by an Inquisitor who recognised its nature as a Null-forged blade. The weapon exists simultaneously in realspace and the Warp.',
  description: 'Base: Force Sword/Witchblade. +3 to attack rolls. +2d4 bonus damage. Through the Veil: affects incorporeal creatures; crits vs psykers/daemons PSY DC 16 or suppressed 1 minute.',
  cost: 'Legendary',
  weight: 3,
  tags: ['melee', 'named', 'psychic', 'null-forged', 'xenos'],
}

export const namedWeaponsRelic: Item[] = [
  handOfOmnissiah,
  thronesWill,
  dragonsFang,
  forgeBreakerCannon,
  stormcallerBow,
  umbralNeedle,
  thunderhandCarbine,
  voidhawkPulse,
  deathsWhisper,
  plasmaBrand,
  emperorsEdge,
  ironclawHammer,
  obliteratorsThorn,
  sacredThrone,
  stellarForge,
  worldsBurden,
  veilParting,
]
