import type { Item } from '../../../types/module'

// ─── Ranged ───────────────────────────────────────────────────────────────────

const inquisitorsMandateRevolver: Item = {
  id: 'inquisitors-mandate',
  name: "The Inquisitor's Mandate",
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Cylinder (6)',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Inquisitorial Authority',
      description: 'Once per rest, you may fire a single shot that deals an additional 2d6 psychic damage. The target must succeed on a WIS save (DC 15) or be frightened until end of their next turn.',
    },
  ],
  lore: 'Carried by Inquisitor Thessaly Vorne of the Ordo Hereticus through forty-seven confirmed purges. The revolver is engraved with the names of heretics she personally executed. She had to add a second cylinder just for the names.',
  description: 'Base: Stub Revolver. +2 to attack rolls. +1d6 bonus damage. Inquisitorial Authority (1/rest): bonus 2d6 psychic + WIS DC 15 or frightened.',
  cost: 'Very Rare',
  weight: 2,
  tags: ['ranged', 'named', 'revolver', 'inquisition'],
}

const solace: Item = {
  id: 'solace',
  name: 'Solace',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'ranged',
  range: { normal: 40, long: 120 },
  damage: '1d6',
  damageType: 'energy',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Light'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Power Pack',
  rechargeable: true,
  itemAbilities: [
    {
      name: 'Mercy Beam',
      description: 'When you reduce a creature to 0 HP, you may choose to stabilise them instead of killing them. Enemies witnessing this must succeed on a WIS save DC 12 or become shaken (disadvantage on attacks) for 1 round.',
    },
  ],
  lore: 'A medicae-configured laspistol belonging to Sister Hospitaller Irenae. She used it to end the suffering of the mortally wounded in war zones. The machine spirit retained something of its purpose — it fires true when the wielder\'s heart is pure.',
  description: 'Base: Laspistol. +2 to attack rolls. +1d6 bonus damage. Mercy Beam: reduce to 0 HP → stabilise instead. Witnesses WIS DC 12 or shaken.',
  cost: 'Very Rare',
  weight: 2,
  tags: ['ranged', 'named', 'las', 'hospitaller'],
}

const widowsKiss: Item = {
  id: 'widows-kiss',
  name: "Widow's Kiss",
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 90 },
  damage: '2d6',
  damageType: 'energy',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'shot',
  ammoCapacity: 8,
  ammoName: 'Plasma Flask',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Widow\'s Mark',
      description: 'On a critical hit, the target becomes Marked. Marked targets take an additional 1d6 energy damage from the first attack each round from any source. The mark lasts until the target or you end your turn resting.',
    },
  ],
  lore: 'A plasma gun that belonged to a Death Cult Assassin known only as "The Widow." She used it exclusively on contract targets. The weapon has been modified to eliminate the usual plasma weapon instability — at the cost of half the maximum charge.',
  description: 'Base: Plasma Gun. +2 to attack rolls. +1d6 bonus damage. No Gets Hot. Widow\'s Mark: crits mark target for +1d6 on first attack per round.',
  cost: 'Very Rare',
  weight: 8,
  tags: ['ranged', 'named', 'plasma', 'assassin'],
}

const spitfire: Item = {
  id: 'spitfire',
  name: 'Spitfire',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 60 },
  damage: '2d6',
  damageType: 'fire',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Spread'],
  ammoType: 'shot',
  ammoCapacity: 6,
  ammoName: 'Promethium Tank',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Inferno Burst',
      description: 'Once per combat, when you fire Spitfire, all creatures in the area of effect must succeed on a DEX save (DC 14) or be set On Fire (1d6 fire damage at start of each turn, action to extinguish). Flammable terrain is also ignited.',
    },
  ],
  lore: 'Constructed by Salamanders Artificer Haestus for a Pyromancer Savant who fought alongside the Chapter during the Promethean Crusade. The promethium mix burns hotter and clings longer than standard formula.',
  description: 'Base: Flamer. +2 to attack rolls. +1d6 bonus damage. Inferno Burst (1/combat): DEX DC 14 or On Fire (1d6/turn, action to extinguish).',
  cost: 'Very Rare',
  weight: 7,
  tags: ['ranged', 'named', 'flamer', 'salamanders'],
}

const tempest: Item = {
  id: 'tempest',
  name: 'Tempest',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d10',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Headhunter',
      description: 'You can use your bonus action to declare a target as Hunted. Until the target is dead or incapacitated, you have advantage on attack rolls against them and your crits deal maximum damage. You can only Hunt one target at a time.',
    },
  ],
  lore: 'A long-las used by Vindicare Temple Assassin Cressida, reassigned after her temple was destroyed in a daemonic incursion. The weapon carries atmospheric sensors and a micro-cogitator that calculates windage, elevation, and target biometrics.',
  description: 'Base: Long-Las/Sniper Rifle. +2 to attack rolls. +1d6 bonus damage. Headhunter (bonus action): advantage vs Hunted target, crits deal max damage.',
  cost: 'Very Rare',
  weight: 7,
  tags: ['ranged', 'named', 'sniper', 'vindicare'],
}

const redemption: Item = {
  id: 'redemption',
  name: 'Redemption',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 80, long: 240 },
  damage: '1d8',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Rapid Fire (1)'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Bolt Magazine',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Oath of the Crusade',
      description: 'When you deal the killing blow to an enemy of Mankind (heretics, mutants, xenos), you gain 5 temporary HP and your next attack roll before the end of your next turn has advantage.',
    },
  ],
  lore: 'A bolt pistol rebuilt into a carbine-configuration by a penitent veteran who swore to kill one hundred heretics before seeking absolution. The tally is engraved in High Gothic on the stock. Current count: 97.',
  description: 'Base: Bolt Carbine. +2 to attack rolls. +1d6 bonus damage. Oath of the Crusade: killing blow vs enemies of Mankind grants 5 temp HP and next attack has advantage.',
  cost: 'Very Rare',
  weight: 5,
  tags: ['ranged', 'named', 'bolt', 'crusader'],
}

const kingmaker: Item = {
  id: 'kingmaker',
  name: 'Kingmaker',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'heavy',
  rangeType: 'ranged',
  range: { normal: 60, long: 240 },
  damage: '2d10',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Mounted', 'Rapid Fire (2)'],
  ammoType: 'belt',
  ammoCapacity: 40,
  ammoName: 'Belt Feed',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Suppressing Fire',
      description: 'As an action, lay down suppressing fire over a 30 ft cone. All creatures in the area must succeed on a STR save (DC 14) or be knocked prone and have their movement halved until the end of their next turn. Uses 10 rounds of belt ammo.',
    },
  ],
  lore: 'A heavy bolter that fell from an Astartes tactical squad and was recovered by the 3rd Armageddon Steel Legion. No one knows how to return it to its rightful owners. Command has decided it is better used than stored.',
  description: 'Base: Heavy Bolter. +2 to attack rolls. +1d6 bonus damage. Suppressing Fire (action): STR DC 14 or prone + halved movement, uses 10 rounds.',
  cost: 'Very Rare',
  weight: 20,
  tags: ['ranged', 'named', 'heavy-bolter', 'armageddon'],
}

const gnaw: Item = {
  id: 'gnaw',
  name: 'Gnaw',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 30, long: 60 },
  damage: '2d6',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Spread'],
  ammoType: 'pack',
  ammoCapacity: 4,
  ammoName: 'Shell Box',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Flechette Storm',
      description: 'Once per rest, fire a super-spread burst that affects all creatures within a 15 ft cone. On a failed DEX save (DC 13) they take full damage; on a success, half. Each failure also applies Bleeding (1d4 at start of turn). Standard action.',
    },
  ],
  lore: 'Built by a Necromundan Escher ganger named "Ripper" who packed the modified choke tube with serrated flechette rounds. The gang\'s rivals called it Gnaw. The name stuck even after Ripper\'s death.',
  description: 'Base: Combat Shotgun. +2 to attack rolls. +1d6 bonus damage. Flechette Storm (1/rest): 15 ft cone, DEX DC 13, fails also Bleed (1d4/turn).',
  cost: 'Very Rare',
  weight: 5,
  tags: ['ranged', 'named', 'shotgun', 'necromunda'],
}

const whisperwind: Item = {
  id: 'whisperwind',
  name: 'Whisperwind',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 150, long: 600 },
  damage: '1d10',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Silent'],
  ammoType: 'pack',
  ammoCapacity: 3,
  ammoName: 'Disc Crystal',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Ghost Shot',
      description: 'Attacks with Whisperwind do not reveal your position. Additionally, if you remain hidden, your first attack each round automatically hits (no attack roll needed, but you must be within range and have line of sight).',
    },
  ],
  lore: 'A Eldar shuriken catapult converted for human use by an Aeldari-trained Ranger who refused to abandon the weapon when she was recruited into an Inquisitorial cell. The xenos mechanism damps sound to near-nothing.',
  description: 'Base: Shuriken Rifle. +2 to attack rolls. +1d6 bonus damage. Ghost Shot: attacks don\'t reveal position; auto-hit first attack per round while hidden.',
  cost: 'Very Rare',
  weight: 5,
  tags: ['ranged', 'named', 'shuriken', 'eldar', 'xenos'],
}

const ashmaker: Item = {
  id: 'ashmaker',
  name: 'Ashmaker',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'ranged',
  range: { normal: 24, long: 48 },
  damage: '4d8',
  damageType: 'heat',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Melta'],
  ammoType: 'shot',
  ammoCapacity: 6,
  ammoName: 'Promethium Canister',
  rechargeable: false,
  itemAbilities: [
    {
      name: 'Reduced to Cinders',
      description: 'Once per rest, you may overheat Ashmaker\'s thermal coil. The next shot deals double dice damage (8d8 instead of 4d8) and ignores all damage resistances. The weapon must cool for 1 round before it can be fired again.',
    },
  ],
  lore: 'A meltagun modified by Adeptus Mechanicus Magos Ferrus during the Siege of Vraks to deal with the particularly hardened fortifications. The additional thermal injectors were "borrowed" from a Dreadnought flamer. The Dreadnought has not been informed.',
  description: 'Base: Meltagun. +2 to attack rolls. +1d6 bonus damage. Reduced to Cinders (1/rest): next shot deals 8d8 and ignores all resistances, then 1 round cooldown.',
  cost: 'Very Rare',
  weight: 10,
  tags: ['ranged', 'named', 'melta', 'mechanicus'],
}

// ─── Melee ────────────────────────────────────────────────────────────────────

const mercysEnd: Item = {
  id: 'mercys-end',
  name: "Mercy's End",
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'slashing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  attackAbility: 'finesse',
  properties: ['Finesse', 'Armor Penetration'],
  itemAbilities: [
    {
      name: 'Executioner\'s Stroke',
      description: 'If the target is Bloodied (below half HP), your attacks with Mercy\'s End score a critical hit on a roll of 18–20 instead of 20. Critical hits also silence the target (no verbal components) until end of their next turn.',
    },
  ],
  lore: 'A mono-sword carried by the last of the Moritat Death Cult, a warrior who considered killing an act of sacred mercy. She died giving this mercy to a daemon prince, driving the blade through its eye. The blade survived. She did not.',
  description: 'Base: Mono-Sword. +2 to attack rolls. +1d6 bonus damage. Executioner\'s Stroke: vs Bloodied targets, crit on 18–20, crits silence until end of next turn.',
  cost: 'Very Rare',
  weight: 3,
  tags: ['melee', 'named', 'sword', 'death-cult'],
}

const silentJudgment: Item = {
  id: 'silent-judgment',
  name: 'Silent Judgment',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Silent'],
  itemAbilities: [
    {
      name: 'No Witnesses',
      description: 'When you kill a creature with Silent Judgment while hidden, you automatically remain hidden from all other creatures who did not directly observe the kill (Perception check DC 18 to notice).',
    },
  ],
  lore: 'A needle pistol/stiletto hybrid weapon confiscated from a Callidus Temple Assassin and reverse-engineered by an Ordo Sicarius analyst. The polymorphine syringe capability was removed. Everything else was kept.',
  description: 'Base: Stiletto/Knife. +2 to attack rolls. +1d6 bonus damage. No Witnesses: kills while hidden remain hidden, DC 18 Perception to notice.',
  cost: 'Very Rare',
  weight: 1,
  tags: ['melee', 'named', 'knife', 'assassin', 'callidus'],
}

const ashesOfFaith: Item = {
  id: 'ashes-of-faith',
  name: 'Ashes of Faith',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'fire',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Two-handed'],
  itemAbilities: [
    {
      name: 'Purifying Flame',
      description: 'On a critical hit, the target is Burning (1d6 fire damage per turn, DEX action to extinguish). Chaos-aligned and daemon targets have disadvantage on the save to extinguish the flame.',
    },
  ],
  lore: 'A power maul that was part of a Confessor\'s holy instruments for forty years before being melted down and reforged into a two-handed weapon after the Confessor\'s parish was destroyed. The machine spirit retains its faith.',
  description: 'Base: Eviscerator (power). +2 to attack rolls. +1d6 bonus damage. Purifying Flame: crits cause Burning (1d6/turn), chaos/daemons have disadvantage to extinguish.',
  cost: 'Very Rare',
  weight: 12,
  tags: ['melee', 'named', 'eviscerator', 'ecclesiarchy'],
}

const ironMaiden: Item = {
  id: 'iron-maiden',
  name: 'Iron Maiden',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d6',
  damageType: 'piercing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed', 'Reach'],
  itemAbilities: [
    {
      name: 'Iron Cage',
      description: 'When you hit a creature of Large or smaller size, you may attempt to grapple them as a bonus action (Athletics vs their Athletics/Acrobatics). While grappled by Iron Maiden\'s mechanism, the target takes 1d6 piercing damage at the start of each of their turns.',
    },
  ],
  lore: 'A man-catcher modified by Iron Hands Techmarine Kastus into a weapon of execution. The original purpose was to capture deserters. The modified purpose is to hold enemies still while the Chapter\'s bolters can reduce them to their component parts.',
  description: 'Base: Man-Catcher/Spear. +2 to attack rolls. +1d6 bonus damage. Iron Cage: on hit, bonus action grapple; grappled target takes 1d6 piercing/turn.',
  cost: 'Very Rare',
  weight: 8,
  tags: ['melee', 'named', 'polearm', 'iron-hands'],
}

const threadCutter: Item = {
  id: 'thread-cutter',
  name: 'Thread-Cutter',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d4',
  damageType: 'slashing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  attackAbility: 'finesse',
  properties: ['Light', 'Finesse', 'Reach'],
  itemAbilities: [
    {
      name: 'Hamstring',
      description: 'On a hit, you may choose to deal no damage but instead reduce the target\'s movement speed by 15 ft until they receive magical healing or spend an action to bind the wound. This can be applied multiple times (min 0 movement).',
    },
  ],
  lore: 'A monofilament whip favoured by Harlequin-trained duelists. The razor-thin blade cuts tendons rather than arteries, slowing prey for the final strike. Technically classified as a "Prohibited Xenos-Derived Weapon" by the Ordos.',
  description: 'Base: Mono-Whip. +2 to attack rolls. +1d6 bonus damage. Hamstring: on hit, reduce movement by 15 ft (stackable to 0) instead of dealing damage.',
  cost: 'Very Rare',
  weight: 2,
  tags: ['melee', 'named', 'whip', 'eldar', 'xenos'],
}

const pyre: Item = {
  id: 'pyre',
  name: 'Pyre',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'fire',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Two-handed'],
  itemAbilities: [
    {
      name: 'Conflagration',
      description: 'When Pyre\'s chain-teeth ignite on a killing blow, each creature within 5 ft of the target must succeed on a DEX save (DC 14) or take 2d6 fire damage as burning tissue spatters outward.',
    },
  ],
  lore: 'An Eviscerator modified for the Frateris Militia during the Reign of Blood with thermal inducers in the chain-teeth. They burned thousands of heretics. After the Reign ended, the weapon was sealed in a reliquary. It was recovered by a Redemptionist Deacon who considered himself successor to that tradition.',
  description: 'Base: Eviscerator. +2 to attack rolls. +1d6 bonus damage. Conflagration: killing blows trigger DEX DC 14 save vs 2d6 fire for adjacent creatures.',
  cost: 'Very Rare',
  weight: 14,
  tags: ['melee', 'named', 'eviscerator', 'frateris-militia'],
}

const oldGrowth: Item = {
  id: 'old-growth',
  name: 'Old Growth',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d8',
  damageType: 'bludgeoning',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Two-handed'],
  itemAbilities: [
    {
      name: 'Root-Deep',
      description: 'On a critical hit, the target must succeed on a STR save (DC 15) or be knocked prone and restrained (can\'t move) until the end of their next turn, as if pinned to the earth.',
    },
  ],
  lore: 'A staff carved from the sacred Nalwood groves of Tanith by a Firstborn Ranger who felt the ancient wood had its own will. He shaped it only removing what the wood offered to release. When Tanith burned, this staff survived. The Ranger didn\'t.',
  description: 'Base: Quarterstaff. +2 to attack rolls. +1d6 bonus damage. Root-Deep: crits force STR DC 15 or prone and restrained until end of next turn.',
  cost: 'Very Rare',
  weight: 4,
  tags: ['melee', 'named', 'staff', 'tanith'],
}

const debtCollector: Item = {
  id: 'debt-collector',
  name: 'Debt Collector',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'bludgeoning',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Light', 'Thrown (20/60)'],
  itemAbilities: [
    {
      name: 'Interest Accrued',
      description: 'If you have already damaged this target with Debt Collector this combat, all subsequent hits deal an additional 1d6 bludgeoning damage (the "interest"). The extra damage increases to 2d6 if you have hit the target 3+ times this combat.',
    },
  ],
  lore: 'A weighted cogitator-chip enforcement club used by a House Delaque information broker\'s muscle. Every outstanding debt is marked on the handle in binary notation. The broker is dead. The debts, technically, survive.',
  description: 'Base: Club/Truncheon. +2 to attack rolls. +1d6 bonus damage. Interest Accrued: repeat hits gain +1d6 (3rd+ hit: +2d6) bonus damage.',
  cost: 'Very Rare',
  weight: 2,
  tags: ['melee', 'named', 'club', 'delaque'],
}

const lastRites: Item = {
  id: 'last-rites',
  name: 'Last Rites',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'simple',
  rangeType: 'melee',
  damage: '1d6',
  damageType: 'bludgeoning',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  versatileDamage: '1d8',
  properties: ['Versatile (1d8)'],
  itemAbilities: [
    {
      name: 'Final Absolution',
      description: 'Once per day, you may invoke the Emperor\'s name when striking. The target must succeed on a CON save (DC 15) or drop to 0 HP. If they succeed, they take maximum damage from the hit instead. This power works only against mortal enemies — not daemons, constructs, or undead.',
    },
  ],
  lore: 'A censer-mace wielded by Arch-Confessor Baraban who gave "last rites" by bludgeoning the condemned to death. The weapon is inscribed with prayers of execution in High Gothic. A cult formed around it after his death.',
  description: 'Base: Mace. +2 to attack rolls. +1d6 bonus damage. Final Absolution (1/day): CON DC 15 or 0 HP; success = max damage. Mortals only.',
  cost: 'Very Rare',
  weight: 4,
  tags: ['melee', 'named', 'mace', 'confessor'],
}

const widowmaker: Item = {
  id: 'widowmaker-blade',
  name: 'Widowmaker',
  type: 'weapon',
  tier: 'artificer',
  isNamed: true,
  weaponCategory: 'martial',
  rangeType: 'melee',
  damage: '2d6',
  damageType: 'slashing',
  bonusAttack: 2,
  bonusDamageDice: '+1d6',
  properties: ['Heavy', 'Two-handed'],
  itemAbilities: [
    {
      name: 'Cleaving Blow',
      description: 'When you kill a creature with Widowmaker, you may immediately make one additional attack against any creature within reach. This free attack does not cost an action and does not trigger additional Cleaving Blows.',
    },
  ],
  lore: 'A power zweihander once wielded by a legendary Cadian officer nicknamed "The Widow" for the trail of bereaved enemies she left on every battlefield. Her regiment was destroyed at the Fall of Cadia. She was not.',
  description: 'Base: Power Zweihander. +2 to attack rolls. +1d6 bonus damage. Cleaving Blow: killing blow triggers immediate free attack vs adjacent target.',
  cost: 'Very Rare',
  weight: 10,
  tags: ['melee', 'named', 'sword', 'cadia'],
}

export const namedWeaponsArtificer: Item[] = [
  inquisitorsMandateRevolver,
  solace,
  widowsKiss,
  spitfire,
  tempest,
  redemption,
  kingmaker,
  gnaw,
  whisperwind,
  ashmaker,
  mercysEnd,
  silentJudgment,
  ashesOfFaith,
  ironMaiden,
  threadCutter,
  pyre,
  oldGrowth,
  debtCollector,
  lastRites,
  widowmaker,
]
