import type { NPC } from '../../../types/module'

// Add NPCs, monsters, and named characters here.
// Each NPC/monster can be its own file for larger bestiaries.
export const coreNPCs: NPC[] = [
  {
    id: 'goblin',
    name: 'Goblin',
    type: 'monster',
    size: 'small',
    alignment: 'Neutral Evil',
    armorClass: 15,
    hitPoints: '2d6',
    speed: 30,
    abilityScores: {
      strength: 8,
      dexterity: 14,
      constitution: 10,
      intelligence: 10,
      wisdom: 8,
      charisma: 8,
    },
    skills: { stealth: 6 },
    senses: ['Darkvision 60ft'],
    languages: ['Common', 'Goblin'],
    challengeRating: 0.25,
    xp: 50,
    traits: [
      {
        name: 'Nimble Escape',
        description: 'The goblin can take the Disengage or Hide action as a bonus action on each of its turns.',
      },
    ],
    actions: [
      {
        name: 'Scimitar',
        description: 'Melee Weapon Attack: +4 to hit, reach 5ft., one target.',
        attackBonus: 4,
        damage: '1d6+2',
        damageType: 'slashing',
      },
      {
        name: 'Shortbow',
        description: 'Ranged Weapon Attack: +4 to hit, range 80/320ft., one target.',
        attackBonus: 4,
        damage: '1d6+2',
        damageType: 'piercing',
      },
    ],
    tags: ['greenskin', 'monster'],
  },
  {
    id: 'orc-warrior',
    name: 'Orc Warrior',
    type: 'monster',
    size: 'medium',
    alignment: 'Chaotic Evil',
    armorClass: 13,
    hitPoints: '2d8+6',
    speed: 30,
    abilityScores: {
      strength: 16,
      dexterity: 12,
      constitution: 16,
      intelligence: 7,
      wisdom: 11,
      charisma: 10,
    },
    senses: ['Darkvision 60ft'],
    languages: ['Common', 'Orc'],
    challengeRating: 0.5,
    xp: 100,
    traits: [
      {
        name: 'Aggressive',
        description: 'As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.',
      },
    ],
    actions: [
      {
        name: 'Greataxe',
        description: 'Melee Weapon Attack: +5 to hit, reach 5ft., one target.',
        attackBonus: 5,
        damage: '1d12+3',
        damageType: 'slashing',
      },
      {
        name: 'Javelin',
        description: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5ft. or range 30/120ft., one target.',
        attackBonus: 5,
        damage: '1d6+3',
        damageType: 'piercing',
      },
    ],
    tags: ['greenskin', 'monster'],
  },
  {
    id: 'empire-guardsman',
    name: 'Empire Guardsman',
    type: 'npc',
    size: 'medium',
    alignment: 'Lawful Neutral',
    armorClass: 16,
    hitPoints: '2d8+2',
    speed: 30,
    abilityScores: {
      strength: 13,
      dexterity: 12,
      constitution: 12,
      intelligence: 10,
      wisdom: 11,
      charisma: 10,
    },
    languages: ['Common'],
    challengeRating: 0.5,
    xp: 100,
    actions: [
      {
        name: 'Longsword',
        description: 'Melee Weapon Attack: +3 to hit, reach 5ft., one target.',
        attackBonus: 3,
        damage: '1d8+1',
        damageType: 'slashing',
      },
      {
        name: 'Crossbow',
        description: 'Ranged Weapon Attack: +3 to hit, range 80/320ft., one target.',
        attackBonus: 3,
        damage: '1d8+1',
        damageType: 'piercing',
      },
    ],
    tags: ['human', 'npc', 'empire'],
  },
]
